namespace DCL.NotificationsBus.NotificationTypes
{
    // SERIOUS WARNING: Changing the order of the elements in the enum will break the selection of icons for specific notifications
    //                  Take a look at the NotificationIcons asset.
    public enum NotificationType
    {
        BID_ACCEPTED,
        BID_RECEIVED,
        EVENTS_STARTED,
        EVENTS_STARTS_SOON,
        GOVERNANCE_ANNOUNCEMENT,
        GOVERNANCE_AUTHORED_PROPOSAL_FINISHED,
        GOVERNANCE_COAUTHOR_REQUESTED,
        GOVERNANCE_NEW_COMMENT_ON_PROJECT_UPDATE,
        GOVERNANCE_NEW_COMMENT_ON_PROPOSAL,
        GOVERNANCE_PROPOSAL_ENACTED,
        GOVERNANCE_VOTING_ENDED_VOTER,
        GOVERNANCE_PITCH_PASSED,
        GOVERNANCE_TENDER_PASSED,
        ITEM_SOLD,
        LAND_RENTAL_ENDED,
        LAND_RENTED,
        REWARD_ASSIGNMENT,
        REWARD_IN_PROGRESS,
        ROYALTIES_EARNED,
        WORLDS_ACCESS_RESTORED,
        WORLDS_ACCESS_RESTRICTED,
        WORLDS_MISSING_RESOURCES,
        WORLDS_PERMISSION_GRANTED,
        WORLDS_PERMISSION_REVOKED,
        BADGE_GRANTED,
        SOCIAL_SERVICE_FRIENDSHIP_REQUEST,
        SOCIAL_SERVICE_FRIENDSHIP_ACCEPTED,

        //Internal notification types
        INTERNAL_ARRIVED_TO_DESTINATION,
        CREDITS_GOAL_COMPLETED,

        STREAMING_KEY_RESET,
        STREAMING_KEY_REVOKE,
        STREAMING_KEY_EXPIRED,
        STREAMING_TIME_EXCEEDED,
        STREAMING_PLACE_UPDATED,

        REFERRAL_INVITED_USERS_ACCEPTED,
        REFERRAL_NEW_TIER_REACHED,

        INTERNAL_DEFAULT_SUCCESS,
        INTERNAL_SERVER_ERROR,
        EVENT_CREATED,
        COMMUNITY_MEMBER_REMOVED,
        COMMUNITY_MEMBER_BANNED,
        COMMUNITY_RENAMED,
        COMMUNITY_DELETED,
        COMMUNITY_REQUEST_TO_JOIN_RECEIVED,
        COMMUNITY_INVITE_RECEIVED,
        COMMUNITY_REQUEST_TO_JOIN_ACCEPTED,
        COMMUNITY_DELETED_CONTENT_VIOLATION,
        COMMUNITY_POST_ADDED,
        COMMUNITY_OWNERSHIP_TRANSFERRED,

        COMMUNITY_VOICE_CHAT_STARTED,

        USER_BANNED_FROM_SCENE,
        USER_UNBANNED_FROM_SCENE,

        TIP_RECEIVED,
    }
}
