addAssignees: author
numberOfAssignees: 1

addReviewers: true
numberOfReviewers: 1
useReviewGroups: true
reviewGroups:
  techleads:
    - mikhail-dcl
    - dalkia
  devs:    
    - sandrade-dcl    
    - lorux0
    - davidejensen
    - popuz
    - pravusjif
    - fcolarich
    - NickKhalow
  qa:
    - Ludmilafantaniella
    - anicalbano
    - dafgreco

filterLabels:
  exclude:
    - "no review"
    - "no QA needed"
