global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using NUnit.Framework;
global using Allure.Net.Commons;
global using Allure.NUnit;
global using Allure.NUnit.Attributes;
global using AltTester.AltTesterSDK.Driver;
global using ExplorerAutomationTests.Common;
global using ExplorerAutomationTests.Views;
global using AltTester.AltTesterSDK.Driver.Notifications;
global using By = AltTester.AltTesterSDK.Driver.By;
