import * as path from 'path'
import { promisify } from 'util'
import { exec } from 'child_process'
import { glob } from 'glob'
import {
  camelToSnakeCase,
  cleanGeneratedCode,
  execute,
  isWin,
  nodeModulesPath,
  normalizePath,
  protocolOutputPath,
  protocolPath,
  protocPath,
  workingDirectory,
} from './helpers'
import * as fs from 'node:fs'
import * as fse from 'fs-extra'

const protocolRawInputPath = normalizePath(path.resolve(protocolPath))

const protocolInputPath = normalizePath(
  path.resolve(__dirname, '../temp/'),
)

// protoc-gen-bitwise plugin and runtime paths (from @dcl/protocol npm package)
const bitwisePluginDir = normalizePath(
  path.resolve(nodeModulesPath, '@dcl/protocol', 'protoc-gen-bitwise'),
)
const bitwisePluginScript = normalizePath(
  path.resolve(bitwisePluginDir, 'plugin.py'),
)
const quantizeRuntimeSrc = normalizePath(
  path.resolve(bitwisePluginDir, 'runtime', 'cs', 'Quantize.cs'),
)

/**
 * Creates a platform-specific wrapper script that protoc can invoke as
 * --plugin=protoc-gen-bitwise=<path>.  The wrapper delegates to the Python
 * plugin.py shipped inside @dcl/protocol.
 */
function createPluginWrapper(dir: string): string {
  if (isWin) {
    const wrapper = path.resolve(dir, 'protoc-gen-bitwise.cmd')
    fs.writeFileSync(
      wrapper,
      `@echo off\r\npy "${bitwisePluginScript}" %*\r\n`,
    )
    return normalizePath(wrapper)
  } else {
    const wrapper = path.resolve(dir, 'protoc-gen-bitwise')
    fs.writeFileSync(
      wrapper,
      `#!/usr/bin/env bash\nexec python3 "${bitwisePluginScript}" "$@"\n`,
    )
    fs.chmodSync(wrapper, 0o755)
    return normalizePath(wrapper)
  }
}

/**
 * Removes bitwise-generated files (*.Bitwise.cs, Quantize.cs) from the output
 * directory so they are regenerated cleanly.
 */
function cleanBitwiseFiles(outputDir: string) {
  const patterns = ['**/*.Bitwise.cs', 'Quantize.cs']
  for (const pattern of patterns) {
    const files = glob.sync(normalizePath(`${outputDir}/${pattern}`))
    for (const file of files) {
      fs.unlinkSync(file)
    }
  }
}

async function main() {
  if (fs.existsSync(protocolInputPath)) {
    fs.rmSync(protocolInputPath, { recursive: true })
  }

  fse.copySync(protocolRawInputPath, protocolInputPath, {
    overwrite: true,
  })

  await execute(`${protocPath} --version`, workingDirectory)

  await buildProtocol()

  fs.rmSync(protocolInputPath, { recursive: true })
}

const regex = new RegExp(/option *\(common.ecs_component_id\) *= *([0-9]+) *;/)

const getComponentId = (text: string): string | null => {
  const res = text.match(regex)
  if (res && res.length >= 1) return res[1]
  return null
}

type ComponentData = { componentName: string; componentId: number }

function generateComponentsEnum(components: ComponentData[]) {
  components.sort((first, second) => first.componentId - second.componentId)
  let content: string = ''

  content += '/* Autogenerated file, DO NOT EDIT! */\n'
  content += 'namespace DCL.ECS7\n'
  content += '{\n'
  content += '    public static class ComponentID \n'
  content += '    {\n'

  content += '        public const int TRANSFORM = 1;\n'
  for (const component of components) {
    let componentUpperCaseName = camelToSnakeCase(
      component.componentName,
    ).toUpperCase()

    content += `        public const int ${componentUpperCaseName} = ${component.componentId.toString()};\n`
  }
  content += '    }\n'
  content += '}\n'

  const outputPath = path.resolve(protocolOutputPath, 'ComponentID.gen.cs')
  fs.writeFileSync(outputPath, content)
}

async function preProcessComponents() {
  const protoFiles = glob.sync(
    normalizePath(
      path.resolve(protocolInputPath, 'decentraland/sdk/components/**/*.proto'),
    ),
  )
  const components: ComponentData[] = []

  for (const file of protoFiles) {
    const content = fs.readFileSync(file).toString()
    const lines = content.split('\n')
    const outputLines = new Array<string>()
    let newComponentId = null

    for (const line of lines) {
      const componentId = getComponentId(line)
      if (componentId) {
        newComponentId = Number(componentId)
      } else if (line.indexOf('common/id.proto') == -1) {
        outputLines.push(line)
      }
    }

    outputLines.push('option csharp_namespace = "DCL.ECSComponents";')

    if (newComponentId) {
      const fileName = path.basename(file)
      const componentName = fileName.replace('.proto', '')
      components.push({
        componentId: newComponentId,
        componentName,
      })
    }

    fs.writeFileSync(file, outputLines.join('\n'))
  }

  generateComponentsEnum(components)
}

function getProtofiles(pattern: string)
{
  return glob
    .sync(
      normalizePath(path.resolve(protocolInputPath, pattern)),
    )
}

const execAsync = promisify(exec)

async function buildProtocol() {
  console.log('Building protocol...')
  cleanGeneratedCode(protocolOutputPath)
  cleanBitwiseFiles(protocolOutputPath)

  await preProcessComponents()

  const protoFiles = getProtofiles('decentraland/**/*.proto')
      .filter((value) => !value.endsWith('id.proto'))
      .filter((value) => !value.endsWith('v1/comms.proto'))
      .filter((value) => !value.endsWith('v2/comms.proto'))
      .filter((value) => !value.endsWith('v3/comms.proto'))

  // Create a platform-specific wrapper so protoc can invoke the Python plugin
  const pluginWrapper = createPluginWrapper(protocolInputPath)

  // Uncomment this line to use the protoc-gen-dclunity plugin and generate the services (rpc dependency)
  //command += ` --plugin=protoc-gen-dclunity=${nodeModulesPath}/protoc-gen-dclunity/dist/index.${isWin ? 'cmd' : 'js'}`
  //command += ` --dclunity_out "${protocolOutputPath}"`
  const baseCommand = [
    protocPath,
    `--csharp_out "${protocolOutputPath}"`,
    '--csharp_opt=file_extension=.gen.cs',
    `--plugin=protoc-gen-bitwise="${pluginWrapper}"`,
    `--bitwise_out="${protocolOutputPath}"`,
    `--proto_path "${protocolInputPath}"`,
  ].join(' ')

  // Split protoFiles into chunks
  const chunkSize = 10
  for (let i = 0; i < protoFiles.length; i += chunkSize) {
    const chunk = protoFiles.slice(i, i + chunkSize)
    const command = `${baseCommand} ${chunk.join(' ')}`

    try {
      await execAsync(command, { cwd: workingDirectory })
    } catch (error) {
      console.error(`Error executing command: ${error}`)
      throw error
    }
  }

  // Copy Quantize.cs runtime (used by the generated bitwise partial classes)
  fs.copyFileSync(
    quantizeRuntimeSrc,
    path.resolve(protocolOutputPath, 'Quantize.cs'),
  )

  console.log('Building protocol... Done!')
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
