cd compressonator/cmp_compressonatorlib;
cmake . -DOPTION_CMP_QT=OFF -DOPTION_CMP_VULKAN=OFF -DOPTION_CMP_DIRECTX=OFF -DOPTION_CMP_OPENCV=OFF -DOPTION_ENABLE_ALL_APPS=OFF -DOPTION_BUILD_CMP_SDK=ON -DOPTION_BUILD_APPS_CMP_CLI=OFF -DOPTION_BUILD_KTX2=OFF -DSIMDE_X86_AVX_ENABLE_NATIVE_ALIASES=ON -DGLM_ENABLE_EXPERIMENTAL=OFF -DGLM_BUILD_LIBRARY=ON; 
make clean;
make -j10;