# The UUAV media sandbox harness, as a function of a nixpkgs instance.
#
# Split out of the root flake so the same expressions serve two consumers: the
# flake's `nix run .#uuav-test`, and the NixOS module in ./nixos-module.nix,
# which needs the media and the scripts without any flake machinery.
{ pkgs, sceneSrc }:

let
  inherit (pkgs) lib;

  # Every asset, generated by ffmpeg from testsrc2/sine at build time. No binary
  # fixture is committed; this derivation is the fixture. It is content-only:
  # nothing here knows a hostname or a port, which is what lets one build serve
  # from any address.
  media = pkgs.runCommand "uuav-test-media"
    {
      nativeBuildInputs = [ pkgs.ffmpeg-full pkgs.openssl ];
      passthru.generator = ./generate-media.sh;
    } ''
    bash ${./generate-media.sh} "$out"
  '';

  libexec = pkgs.runCommand "uuav-test-libexec" { } ''
    mkdir -p $out
    cp ${./pki.sh}          $out/pki.sh
    cp ${./check.sh}        $out/check.sh
    cp ${./stall-server.py} $out/stall-server.py
  '';

  runtimeInputs = [
    pkgs.bash
    pkgs.coreutils
    pkgs.curl
    pkgs.ffmpeg-full # ffprobe, for --check
    pkgs.gnugrep
    pkgs.gnused
    pkgs.jq
    pkgs.openssl
    pkgs.python3
  ];
  # nix itself is deliberately not a runtime input: writeShellApplication
  # prepends to PATH rather than replacing it, so the ambient nix is reachable
  # for the UUAV_TEST_SDK_FLAKE fallback, and the harness closure stays small.

  runner = pkgs.writeShellApplication {
    name = "uuav-test";
    inherit runtimeInputs;
    # writeShellApplication runs shellcheck; the substituted placeholders are
    # plain string replacement, so do the substitution after the check.
    text = builtins.replaceStrings
      [ "@media@" "@scene@" "@libexec@" "@nginx@" ]
      [ "${media}" "${sceneSrc}" "${libexec}" "${pkgs.nginx}" ]
      (builtins.readFile ./runner.sh);
  };
in
{
  inherit media libexec runner;

  # `nix build .#uuav-test-manifest` - the media half of the manifest on its own,
  # for anything that wants the case table without standing the servers up.
  cases = pkgs.runCommand "uuav-test-cases.json" { } ''
    cp ${media}/cases.json $out
  '';
}
