using CRDT.Protocol;
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading;

namespace CrdtEcsBridge
{
    /// <summary>
    ///     Filters Creator Hub editor-only and tooling components that leak from
    ///     <c>main.composite</c> into <c>main.crdt</c> via the composite-to-CRDT converter
    ///     (<c>dumpEngineToCrdtCommands</c>).
    ///     <para />
    ///     Two detection layers:
    ///     <list type="number">
    ///         <item>
    ///             Named Creator Hub components — <c>inspector::*</c>, specific
    ///             <c>asset-packs::</c> tooling metadata, <c>composite::root</c>. Identified by
    ///             computing the same CRC-32 based component ID the SDK uses
    ///             (<c>@dcl/ecs componentNumberFromName</c>).
    ///         </item>
    ///         <item>
    ///             Phantom Creator Hub tags — custom components (ID &gt; 2048) with zero-length
    ///             data, generated by the Builder to classify entities
    ///             (e.g. <c>cube-id</c>, <c>sphere-id</c>).
    ///         </item>
    ///     </list>
    ///     <para />
    ///     Thread-safe: the blocked-ID set is built once via racy lazy init (idempotent,
    ///     published with a volatile write). The hot path is a lock-free
    ///     <see cref="HashSet{T}.Contains" /> with zero allocations.
    /// </summary>
    public static class CreatorHubComponentFilter
    {
        /// <summary>
        ///     Core (proto-generated) components live in the range 1–2047.
        ///     Everything above is a dynamic component whose ID is derived from its name.
        ///     Source: <c>@dcl/ecs/src/components/component-number.ts</c>
        /// </summary>
        private const uint MAX_STATIC_COMPONENT = 1 << 11; // 2048

        /// <summary>
        ///     Creator Hub component names that must never enter the renderer CRDT state.
        ///     <list type="bullet">
        ///         <item>
        ///             <c>inspector::*</c>  — Creator Hub workspace state
        ///             (<c>versioning/base-names.ts</c>)
        ///         </item>
        ///         <item>
        ///             <c>asset-packs::</c> — specific tooling-only components
        ///             (<c>NOT_SYNC_COMPONENTS_NAMES</c> in <c>@dcl/sdk</c>)
        ///         </item>
        ///         <item>
        ///             <c>composite::</c>   — conversion metadata, skipped during composite
        ///             instancing
        ///         </item>
        ///     </list>
        /// </summary>
        private static readonly string[] CREATOR_HUB_COMPONENT_NAMES =
        {
            // inspector:: — full set from creator-hub/packages/inspector versioning registry
            "inspector::Selection",
            "inspector::Nodes",
            "inspector::TransformConfig",
            "inspector::Hide",
            "inspector::Lock",
            "inspector::Ground",
            "inspector::Tile",
            "inspector::CustomAsset",
            "inspector::Config",
            "inspector::UIState",
            "inspector::Scene",
            "inspector::SceneMetadata",
            "inspector::SceneMetadata-v1",
            "inspector::SceneMetadata-v2",
            "inspector::SceneMetadata-v3",
            "inspector::SceneMetadata-v4",

            // asset-packs:: — tooling metadata only (ActionTypes/Script are in SDK NOT_SYNC list)
            "asset-packs::ActionTypes",
            "asset-packs::Script",
            "asset-packs::Placeholder",

            // composite:: — composite-to-CRDT conversion metadata
            "composite::root",
        };

        /// <summary>
        ///     Lazily initialised, then immutable. Racy init is safe because the result is
        ///     always identical and <see cref="Volatile.Write{T}" /> guarantees a
        ///     fully-constructed object is published.
        /// </summary>
        private static HashSet<int>? blockedIds;

        /// <summary>
        ///     Returns <c>true</c> if the CRDT message carries a Creator Hub component or a
        ///     phantom Creator Hub tag and should be dropped before entering the CRDT protocol
        ///     state. Only meaningful for component-bearing message types (PUT / DELETE / APPEND).
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool ShouldFilter(in CRDTMessage message) =>
            IsCreatorHubComponent(message.ComponentId) || IsPhantomCreatorHubTag(in message);

        /// <summary>
        ///     Returns <c>true</c> if the component ID belongs to a known Creator Hub component.
        ///     Core components (ID ≤ 2048) are never blocked.
        ///     Zero allocations on the hot path.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool IsCreatorHubComponent(int componentId)
        {
            if (unchecked((uint)componentId) <= MAX_STATIC_COMPONENT)
                return false;

            return BlockedIds.Contains(componentId);
        }

        /// <summary>
        ///     Detects phantom Creator Hub tags: custom components (ID &gt; 2048) with empty
        ///     data. These are Builder-generated entity classification markers
        ///     (e.g. <c>cube-id</c>, <c>sphere-id</c>) that serialize as zero-byte payloads
        ///     from empty map schemas.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool IsPhantomCreatorHubTag(in CRDTMessage message) =>
            unchecked((uint)message.ComponentId) > MAX_STATIC_COMPONENT
            && message.Data.Memory.IsEmpty;

        /// <summary>
        ///     Computes a component ID from its qualified name using the same algorithm as
        ///     <c>@dcl/ecs componentNumberFromName</c>: standard CRC-32 (ISO 3309) of a
        ///     128-byte zero-padded UTF-8 buffer, plus 2048.
        ///     Uses <c>stackalloc</c> — zero heap allocations.
        /// </summary>
        public static int ComponentIdFromName(string name)
        {
            Span<byte> buf = stackalloc byte[128];
            Encoding.UTF8.GetBytes(name.AsSpan(), buf);
            uint crc = ComputeCrc32(buf);
            return unchecked((int)((crc + MAX_STATIC_COMPONENT) & 0xFFFFFFFF));
        }

#region Internals
        private static HashSet<int> BlockedIds
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Volatile.Read(ref blockedIds) ?? InitBlockedIds();
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        private static HashSet<int> InitBlockedIds()
        {
            var set = new HashSet<int>(CREATOR_HUB_COMPONENT_NAMES.Length);

            foreach (string name in CREATOR_HUB_COMPONENT_NAMES)
                set.Add(ComponentIdFromName(name));

            Volatile.Write(ref blockedIds, set);
            return set;
        }

        private static unsafe uint ComputeCrc32(ReadOnlySpan<byte> data)
        {
            var crc = 0xFFFFFFFF;

            fixed (byte* pData = data)
            fixed (uint* pTable = CRC32_TABLE)
            {
                byte* end = pData + data.Length;

                for (byte* p = pData; p < end; p++)
                    crc = pTable[(crc ^ *p) & 0xFF] ^ (crc >> 8);
            }

            return crc ^ 0xFFFFFFFF;
        }

        // Standard CRC-32 lookup table (polynomial 0xEDB88320, reflected form of 0x04C11DB7).
        private static readonly uint[] CRC32_TABLE = GenerateCrc32Table();

        private static uint[] GenerateCrc32Table()
        {
            var table = new uint[256];

            for (uint i = 0; i < 256; i++)
            {
                uint crc = i;

                for (var j = 0; j < 8; j++)
                    crc = (crc & 1) != 0 ? (crc >> 1) ^ 0xEDB88320u : crc >> 1;

                table[i] = crc;
            }

            return table;
        }
#endregion
    }
}
