name: 'Version'
description: 'Parse, update and format the given tag for onward operations'
inputs:
  tag:
    description: 'Formated version tag. If not set it uses latest version tag (v[0-9]*)'
    required: false
outputs:
  latest_version:
    description: 'Latest available version tag in repo'
    value: ${{ steps.get_latest_version_tag.outputs.tag }}
  full_version:
    description: 'v1.2.3-name-branch'
    value: ${{ steps.parser.outputs.full_version }}
  tag_version:
    description: 'v1.2.3-name'
    value: ${{ steps.parser.outputs.tag_version }}
  next_full_version:
    description: 'v1.3.0-name-branch'
    value: ${{ steps.parser.outputs.next_full_version }}
  next_tag_version:
    description: 'v1.3.0-name'
    value: ${{ steps.parser.outputs.next_tag_version }}
runs:
  using: "composite"
  steps:
    - name: Get latest version tag
      if: ${{ !inputs.tag }}
      id: get_latest_version_tag
      run: echo "tag=$(git describe --tags --match='v[0-9]*' --long)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Parse version tag
      id: parser
      run: |
        #!/bin/bash
        TAG=${{ inputs.tag || steps.get_latest_version_tag.outputs.tag }}

        # Extract version components (expecting v1.2.3-name-0-commitsha)
        if [[ $TAG =~ ^v([0-9]+)\.([0-9]+).([0-9]+)-(.+)-([0-9]+)-(.+)$ ]]; then
          MAJOR="${BASH_REMATCH[1]}"
          MINOR="${BASH_REMATCH[2]}"
          BUILD="${BASH_REMATCH[3]}"
          NAME="${BASH_REMATCH[4]}"
          COMMITS_SINCE="${BASH_REMATCH[5]}"
          
          echo "Version parsed match:"
          echo "[Major]: $MAJOR"
          echo "[Minor]: $MINOR"
          echo "[Build]: $BUILD"
          echo "[Name]: $NAME"
          echo "Commits since tag: $COMMITS_SINCE"
        else
          echo "Failling! Tag does not match expected format: $TAG"
          exit 1
        fi

        # Not sure this works as expected!
        if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
          BRANCH_NAME="$GITHUB_HEAD_REF"
        else
          BRANCH_NAME=$(echo "$GITHUB_REF" | cut -d'/' -f 3)
        fi
          
        FULLVER="v${MAJOR}.${MINOR}.$((BUILD + COMMITS_SINCE))-${NAME}-${BRANCH_NAME}"
        echo "Full version: $FULLVER"
        echo "full_version=$FULLVER" >> "$GITHUB_OUTPUT"
        
        TAGVER="v${MAJOR}.${MINOR}.$((BUILD + COMMITS_SINCE))-${NAME}"
        echo "Tag version: $TAGVER"
        echo "tag_version=$TAGVER" >> "$GITHUB_OUTPUT"
        
        NEXT_FULLVER="v${MAJOR}.$((MINOR + 1)).0-${NAME}-${BRANCH_NAME}"
        echo "Next full version: $NEXT_FULLVER"
        echo "next_full_version=$NEXT_FULLVER" >> "$GITHUB_OUTPUT"
                                                                  
        NEXT_TAGVER="v${MAJOR}.$((MINOR + 1)).0-${NAME}"
        echo "Next tag version: $NEXT_TAGVER"
        echo "next_tag_version=$NEXT_TAGVER" >> "$GITHUB_OUTPUT"
      shell: bash
