#!/usr/bin/env bash
# Run ReSharper InspectCode
# Single source of truth for the inspection invocation
#
# Usage: run-inspectcode.sh [solution] [output_report]
#   solution       default: Explorer/Explorer.sln
#   output_report  default: InspectCodeReport.json
#
# Exit codes: 0 = inspection ran; 3 = ReSharper CLI not found (caller decides what to do).
set -euo pipefail

solution="${1:-Explorer/Explorer.sln}"
output="${2:-InspectCodeReport.json}"

# Resolve the CLI: explicit RSHARP_HOME, the CI layout (./rsharp), then a common local install.
find_cli() {
    local d
    for d in "${RSHARP_HOME:-}" "rsharp" "$HOME/Downloads/rsharp"; do
        if [ -n "$d" ] && [ -x "$d/inspectcode.sh" ]; then
            echo "$d/inspectcode.sh"
            return 0
        fi
    done
    return 1
}

cli="$(find_cli)" || {
    echo "run-inspectcode: ReSharper CLI not found (looked in \$RSHARP_HOME, ./rsharp, ~/Downloads/rsharp)." >&2
    exit 3
}

# The JetBrains.Unity extension nupkg is downloaded next to the CLI by download-resharper.sh;
# point --source here so it loads offline instead of hitting the plugin gallery.
cli_dir="$(dirname "$cli")"

# --no-build requires the solution to be freshly generated by Unity in the SAME
# environment this script runs in (CI: inside the Unity container; locally: your
# machine), so the absolute reference paths in the generated csprojs resolve.
# Unity already compiled everything during solution sync — no second build needed.
#
# --eXtensions=JetBrains.Unity makes the CLI Unity-aware, exactly like Rider's Unity
# plugin: without it 'Assets'/'Packages' are treated as namespace providers and every
# 'Assets/DCL/...' file (namespaced 'DCL....') triggers a false CheckNamespace warning.
# --source loads the extension from the nupkg bundled next to the CLI (offline).
"$cli" "$solution" \
    --no-build \
    --eXtensions=JetBrains.Unity \
    --source="$cli_dir" \
    --verbosity=INFO \
    --properties:Configuration=Debug \
    --disable-settings-layers:SolutionPersonal \
    --output="$output"
