import { IntegrationTestContext } from "./source/integrationTestsSource";

export async function getRealmTest(result: IntegrationTestContext): Promise<void> {

}

export async function getWorldTimeTest(result: IntegrationTestContext): Promise<void> {

}

export async function readFileTest(result: IntegrationTestContext): Promise<void> {

}

export async function getSceneInformationTest(result: IntegrationTestContext): Promise<void> {

}