// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: decentraland/sdk/components/audio_source_effect.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DCL.ECSComponents {

  /// <summary>Holder for reflection information generated from decentraland/sdk/components/audio_source_effect.proto</summary>
  public static partial class AudioSourceEffectReflection {

    #region Descriptor
    /// <summary>File descriptor for decentraland/sdk/components/audio_source_effect.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AudioSourceEffectReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjVkZWNlbnRyYWxhbmQvc2RrL2NvbXBvbmVudHMvYXVkaW9fc291cmNlX2Vm",
            "ZmVjdC5wcm90bxIbZGVjZW50cmFsYW5kLnNkay5jb21wb25lbnRzIpoHChNQ",
            "QkF1ZGlvU291cmNlRWZmZWN0Eh0KEHRhcmdldF9hdmF0YXJfaWQYASABKAlI",
            "AIgBARIUCgdzaWxlbmNlGAkgASgISAGIAQESGQoMZGVzcGF0aWFsaXplGAog",
            "ASgISAKIAQESUgoGcmV2ZXJiGAsgASgLMj0uZGVjZW50cmFsYW5kLnNkay5j",
            "b21wb25lbnRzLlBCQXVkaW9Tb3VyY2VFZmZlY3QuUmV2ZXJiRWZmZWN0SAOI",
            "AQESTgoEZWNobxgMIAEoCzI7LmRlY2VudHJhbGFuZC5zZGsuY29tcG9uZW50",
            "cy5QQkF1ZGlvU291cmNlRWZmZWN0LkVjaG9FZmZlY3RIBIgBARJaCgdhbXBs",
            "aWZ5GA0gASgLMkQuZGVjZW50cmFsYW5kLnNkay5jb21wb25lbnRzLlBCQXVk",
            "aW9Tb3VyY2VFZmZlY3QuQW1wbGlmaWNhdGlvbkVmZmVjdEgFiAEBGoUBChNB",
            "bXBsaWZpY2F0aW9uRWZmZWN0Eh4KEXZvbHVtZV9tdWx0aXBsaWVyGAEgASgC",
            "SACIAQESIAoTZGlzdGFuY2VfbXVsdGlwbGllchgCIAEoAkgBiAEBQhQKEl92",
            "b2x1bWVfbXVsdGlwbGllckIWChRfZGlzdGFuY2VfbXVsdGlwbGllchq3AQoM",
            "UmV2ZXJiRWZmZWN0ElIKBnByZXNldBgBIAEoDjI9LmRlY2VudHJhbGFuZC5z",
            "ZGsuY29tcG9uZW50cy5QQkF1ZGlvU291cmNlRWZmZWN0LlJldmVyYlByZXNl",
            "dEgAiAEBEhQKB3dldF9taXgYAiABKAJIAYgBARIXCgpkZWNheV90aW1lGAMg",
            "ASgCSAKIAQFCCQoHX3ByZXNldEIKCghfd2V0X21peEINCgtfZGVjYXlfdGlt",
            "ZRpOCgpFY2hvRWZmZWN0EhUKCGRlbGF5X21zGAEgASgCSACIAQESEgoFZGVj",
            "YXkYAiABKAJIAYgBAUILCglfZGVsYXlfbXNCCAoGX2RlY2F5IkkKDFJldmVy",
            "YlByZXNldBILCgdSUF9ST09NEAASDAoIUlBfQVJFTkEQARILCgdSUF9DQVZF",
            "EAISEQoNUlBfQVVESVRPUklVTRADQhMKEV90YXJnZXRfYXZhdGFyX2lkQgoK",
            "CF9zaWxlbmNlQg8KDV9kZXNwYXRpYWxpemVCCQoHX3JldmVyYkIHCgVfZWNo",
            "b0IKCghfYW1wbGlmeUoECAIQA0IUqgIRRENMLkVDU0NvbXBvbmVudHNiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DCL.ECSComponents.PBAudioSourceEffect), global::DCL.ECSComponents.PBAudioSourceEffect.Parser, new[]{ "TargetAvatarId", "Silence", "Despatialize", "Reverb", "Echo", "Amplify" }, new[]{ "TargetAvatarId", "Silence", "Despatialize", "Reverb", "Echo", "Amplify" }, new[]{ typeof(global::DCL.ECSComponents.PBAudioSourceEffect.Types.ReverbPreset) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::DCL.ECSComponents.PBAudioSourceEffect.Types.AmplificationEffect), global::DCL.ECSComponents.PBAudioSourceEffect.Types.AmplificationEffect.Parser, new[]{ "VolumeMultiplier", "DistanceMultiplier" }, new[]{ "VolumeMultiplier", "DistanceMultiplier" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DCL.ECSComponents.PBAudioSourceEffect.Types.ReverbEffect), global::DCL.ECSComponents.PBAudioSourceEffect.Types.ReverbEffect.Parser, new[]{ "Preset", "WetMix", "DecayTime" }, new[]{ "Preset", "WetMix", "DecayTime" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DCL.ECSComponents.PBAudioSourceEffect.Types.EchoEffect), global::DCL.ECSComponents.PBAudioSourceEffect.Types.EchoEffect.Parser, new[]{ "DelayMs", "Decay" }, new[]{ "DelayMs", "Decay" }, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// The AudioSourceEffect component applies audio post-processing effects to a target avatar's
  /// incoming voice-chat audio stream (v1 = nearby voice chat only).
  ///
  /// Each component may carry one or more effects via flat optional fields. Multiple components
  /// targeting the same avatar are aggregated Explorer-side in deterministic order (by source
  /// CRDT entity ID) to form an effect chain. A `silence` field set to true short-circuits the
  /// entire chain for that target avatar.
  ///
  /// Empty or unset `target_avatar_id` renders the component inert (no-op).
  ///
  /// Forward-compatibility: v2 will add field 2 (`target_audio_entity`, uint32) to support
  /// per-PBAudioSource effect targeting. Reserved IDs 1402 and 1403 are allocated to sibling
  /// components: PBAudioListenerEffect and PBAudioSourceEffectResult, respectively.
  /// </summary>
  public sealed partial class PBAudioSourceEffect : pb::IMessage<PBAudioSourceEffect>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PBAudioSourceEffect> _parser = new pb::MessageParser<PBAudioSourceEffect>(() => new PBAudioSourceEffect());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PBAudioSourceEffect> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DCL.ECSComponents.AudioSourceEffectReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBAudioSourceEffect() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBAudioSourceEffect(PBAudioSourceEffect other) : this() {
      _hasBits0 = other._hasBits0;
      targetAvatarId_ = other.targetAvatarId_;
      silence_ = other.silence_;
      despatialize_ = other.despatialize_;
      reverb_ = other.reverb_ != null ? other.reverb_.Clone() : null;
      echo_ = other.echo_ != null ? other.echo_.Clone() : null;
      amplify_ = other.amplify_ != null ? other.amplify_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBAudioSourceEffect Clone() {
      return new PBAudioSourceEffect(this);
    }

    /// <summary>Field number for the "target_avatar_id" field.</summary>
    public const int TargetAvatarIdFieldNumber = 1;
    private string targetAvatarId_;
    /// <summary>
    /// Target avatar's eth address. Case-insensitive on Explorer side. Empty = inert.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TargetAvatarId {
      get { return targetAvatarId_ ?? ""; }
      set {
        targetAvatarId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "target_avatar_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTargetAvatarId {
      get { return targetAvatarId_ != null; }
    }
    /// <summary>Clears the value of the "target_avatar_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTargetAvatarId() {
      targetAvatarId_ = null;
    }

    /// <summary>Field number for the "silence" field.</summary>
    public const int SilenceFieldNumber = 9;
    private bool silence_;
    /// <summary>
    /// Short-circuits all other effects targeting the same address.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Silence {
      get { if ((_hasBits0 & 1) != 0) { return silence_; } else { return false; } }
      set {
        _hasBits0 |= 1;
        silence_ = value;
      }
    }
    /// <summary>Gets whether the "silence" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSilence {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "silence" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSilence() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "despatialize" field.</summary>
    public const int DespatializeFieldNumber = 10;
    private bool despatialize_;
    /// <summary>
    /// Removes spatial blend; applies constant volume regardless of distance.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Despatialize {
      get { if ((_hasBits0 & 2) != 0) { return despatialize_; } else { return false; } }
      set {
        _hasBits0 |= 2;
        despatialize_ = value;
      }
    }
    /// <summary>Gets whether the "despatialize" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDespatialize {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "despatialize" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDespatialize() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "reverb" field.</summary>
    public const int ReverbFieldNumber = 11;
    private global::DCL.ECSComponents.PBAudioSourceEffect.Types.ReverbEffect reverb_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DCL.ECSComponents.PBAudioSourceEffect.Types.ReverbEffect Reverb {
      get { return reverb_; }
      set {
        reverb_ = value;
      }
    }

    /// <summary>Field number for the "echo" field.</summary>
    public const int EchoFieldNumber = 12;
    private global::DCL.ECSComponents.PBAudioSourceEffect.Types.EchoEffect echo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DCL.ECSComponents.PBAudioSourceEffect.Types.EchoEffect Echo {
      get { return echo_; }
      set {
        echo_ = value;
      }
    }

    /// <summary>Field number for the "amplify" field.</summary>
    public const int AmplifyFieldNumber = 13;
    private global::DCL.ECSComponents.PBAudioSourceEffect.Types.AmplificationEffect amplify_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DCL.ECSComponents.PBAudioSourceEffect.Types.AmplificationEffect Amplify {
      get { return amplify_; }
      set {
        amplify_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PBAudioSourceEffect);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PBAudioSourceEffect other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TargetAvatarId != other.TargetAvatarId) return false;
      if (Silence != other.Silence) return false;
      if (Despatialize != other.Despatialize) return false;
      if (!object.Equals(Reverb, other.Reverb)) return false;
      if (!object.Equals(Echo, other.Echo)) return false;
      if (!object.Equals(Amplify, other.Amplify)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasTargetAvatarId) hash ^= TargetAvatarId.GetHashCode();
      if (HasSilence) hash ^= Silence.GetHashCode();
      if (HasDespatialize) hash ^= Despatialize.GetHashCode();
      if (reverb_ != null) hash ^= Reverb.GetHashCode();
      if (echo_ != null) hash ^= Echo.GetHashCode();
      if (amplify_ != null) hash ^= Amplify.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasTargetAvatarId) {
        output.WriteRawTag(10);
        output.WriteString(TargetAvatarId);
      }
      if (HasSilence) {
        output.WriteRawTag(72);
        output.WriteBool(Silence);
      }
      if (HasDespatialize) {
        output.WriteRawTag(80);
        output.WriteBool(Despatialize);
      }
      if (reverb_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(Reverb);
      }
      if (echo_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(Echo);
      }
      if (amplify_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(Amplify);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasTargetAvatarId) {
        output.WriteRawTag(10);
        output.WriteString(TargetAvatarId);
      }
      if (HasSilence) {
        output.WriteRawTag(72);
        output.WriteBool(Silence);
      }
      if (HasDespatialize) {
        output.WriteRawTag(80);
        output.WriteBool(Despatialize);
      }
      if (reverb_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(Reverb);
      }
      if (echo_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(Echo);
      }
      if (amplify_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(Amplify);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasTargetAvatarId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TargetAvatarId);
      }
      if (HasSilence) {
        size += 1 + 1;
      }
      if (HasDespatialize) {
        size += 1 + 1;
      }
      if (reverb_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Reverb);
      }
      if (echo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Echo);
      }
      if (amplify_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Amplify);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PBAudioSourceEffect other) {
      if (other == null) {
        return;
      }
      if (other.HasTargetAvatarId) {
        TargetAvatarId = other.TargetAvatarId;
      }
      if (other.HasSilence) {
        Silence = other.Silence;
      }
      if (other.HasDespatialize) {
        Despatialize = other.Despatialize;
      }
      if (other.reverb_ != null) {
        if (reverb_ == null) {
          Reverb = new global::DCL.ECSComponents.PBAudioSourceEffect.Types.ReverbEffect();
        }
        Reverb.MergeFrom(other.Reverb);
      }
      if (other.echo_ != null) {
        if (echo_ == null) {
          Echo = new global::DCL.ECSComponents.PBAudioSourceEffect.Types.EchoEffect();
        }
        Echo.MergeFrom(other.Echo);
      }
      if (other.amplify_ != null) {
        if (amplify_ == null) {
          Amplify = new global::DCL.ECSComponents.PBAudioSourceEffect.Types.AmplificationEffect();
        }
        Amplify.MergeFrom(other.Amplify);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            TargetAvatarId = input.ReadString();
            break;
          }
          case 72: {
            Silence = input.ReadBool();
            break;
          }
          case 80: {
            Despatialize = input.ReadBool();
            break;
          }
          case 90: {
            if (reverb_ == null) {
              Reverb = new global::DCL.ECSComponents.PBAudioSourceEffect.Types.ReverbEffect();
            }
            input.ReadMessage(Reverb);
            break;
          }
          case 98: {
            if (echo_ == null) {
              Echo = new global::DCL.ECSComponents.PBAudioSourceEffect.Types.EchoEffect();
            }
            input.ReadMessage(Echo);
            break;
          }
          case 106: {
            if (amplify_ == null) {
              Amplify = new global::DCL.ECSComponents.PBAudioSourceEffect.Types.AmplificationEffect();
            }
            input.ReadMessage(Amplify);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            TargetAvatarId = input.ReadString();
            break;
          }
          case 72: {
            Silence = input.ReadBool();
            break;
          }
          case 80: {
            Despatialize = input.ReadBool();
            break;
          }
          case 90: {
            if (reverb_ == null) {
              Reverb = new global::DCL.ECSComponents.PBAudioSourceEffect.Types.ReverbEffect();
            }
            input.ReadMessage(Reverb);
            break;
          }
          case 98: {
            if (echo_ == null) {
              Echo = new global::DCL.ECSComponents.PBAudioSourceEffect.Types.EchoEffect();
            }
            input.ReadMessage(Echo);
            break;
          }
          case 106: {
            if (amplify_ == null) {
              Amplify = new global::DCL.ECSComponents.PBAudioSourceEffect.Types.AmplificationEffect();
            }
            input.ReadMessage(Amplify);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the PBAudioSourceEffect message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// Enumeration of reverb presets.
      /// </summary>
      public enum ReverbPreset {
        /// <summary>
        /// Small room acoustics.
        /// </summary>
        [pbr::OriginalName("RP_ROOM")] RpRoom = 0,
        /// <summary>
        /// Large arena acoustics.
        /// </summary>
        [pbr::OriginalName("RP_ARENA")] RpArena = 1,
        /// <summary>
        /// Cavern acoustics.
        /// </summary>
        [pbr::OriginalName("RP_CAVE")] RpCave = 2,
        /// <summary>
        /// Large auditorium acoustics.
        /// </summary>
        [pbr::OriginalName("RP_AUDITORIUM")] RpAuditorium = 3,
      }

      /// <summary>
      /// Amplifies or attenuates audio, with optional distance scaling override.
      /// </summary>
      public sealed partial class AmplificationEffect : pb::IMessage<AmplificationEffect>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<AmplificationEffect> _parser = new pb::MessageParser<AmplificationEffect>(() => new AmplificationEffect());
        private pb::UnknownFieldSet _unknownFields;
        private int _hasBits0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<AmplificationEffect> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::DCL.ECSComponents.PBAudioSourceEffect.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public AmplificationEffect() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public AmplificationEffect(AmplificationEffect other) : this() {
          _hasBits0 = other._hasBits0;
          volumeMultiplier_ = other.volumeMultiplier_;
          distanceMultiplier_ = other.distanceMultiplier_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public AmplificationEffect Clone() {
          return new AmplificationEffect(this);
        }

        /// <summary>Field number for the "volume_multiplier" field.</summary>
        public const int VolumeMultiplierFieldNumber = 1;
        private float volumeMultiplier_;
        /// <summary>
        /// default: 2.0, clamped to [0.0, 4.0] on Explorer.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float VolumeMultiplier {
          get { if ((_hasBits0 & 1) != 0) { return volumeMultiplier_; } else { return 0F; } }
          set {
            _hasBits0 |= 1;
            volumeMultiplier_ = value;
          }
        }
        /// <summary>Gets whether the "volume_multiplier" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasVolumeMultiplier {
          get { return (_hasBits0 & 1) != 0; }
        }
        /// <summary>Clears the value of the "volume_multiplier" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearVolumeMultiplier() {
          _hasBits0 &= ~1;
        }

        /// <summary>Field number for the "distance_multiplier" field.</summary>
        public const int DistanceMultiplierFieldNumber = 2;
        private float distanceMultiplier_;
        /// <summary>
        /// default: 2.0, clamped to [0.1, 10.0] on Explorer.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float DistanceMultiplier {
          get { if ((_hasBits0 & 2) != 0) { return distanceMultiplier_; } else { return 0F; } }
          set {
            _hasBits0 |= 2;
            distanceMultiplier_ = value;
          }
        }
        /// <summary>Gets whether the "distance_multiplier" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasDistanceMultiplier {
          get { return (_hasBits0 & 2) != 0; }
        }
        /// <summary>Clears the value of the "distance_multiplier" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearDistanceMultiplier() {
          _hasBits0 &= ~2;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as AmplificationEffect);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(AmplificationEffect other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(VolumeMultiplier, other.VolumeMultiplier)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(DistanceMultiplier, other.DistanceMultiplier)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (HasVolumeMultiplier) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(VolumeMultiplier);
          if (HasDistanceMultiplier) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(DistanceMultiplier);
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (HasVolumeMultiplier) {
            output.WriteRawTag(13);
            output.WriteFloat(VolumeMultiplier);
          }
          if (HasDistanceMultiplier) {
            output.WriteRawTag(21);
            output.WriteFloat(DistanceMultiplier);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (HasVolumeMultiplier) {
            output.WriteRawTag(13);
            output.WriteFloat(VolumeMultiplier);
          }
          if (HasDistanceMultiplier) {
            output.WriteRawTag(21);
            output.WriteFloat(DistanceMultiplier);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (HasVolumeMultiplier) {
            size += 1 + 4;
          }
          if (HasDistanceMultiplier) {
            size += 1 + 4;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(AmplificationEffect other) {
          if (other == null) {
            return;
          }
          if (other.HasVolumeMultiplier) {
            VolumeMultiplier = other.VolumeMultiplier;
          }
          if (other.HasDistanceMultiplier) {
            DistanceMultiplier = other.DistanceMultiplier;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 13: {
                VolumeMultiplier = input.ReadFloat();
                break;
              }
              case 21: {
                DistanceMultiplier = input.ReadFloat();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 13: {
                VolumeMultiplier = input.ReadFloat();
                break;
              }
              case 21: {
                DistanceMultiplier = input.ReadFloat();
                break;
              }
            }
          }
        }
        #endif

      }

      /// <summary>
      /// Applies reverb via preset or custom parameters.
      /// </summary>
      public sealed partial class ReverbEffect : pb::IMessage<ReverbEffect>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<ReverbEffect> _parser = new pb::MessageParser<ReverbEffect>(() => new ReverbEffect());
        private pb::UnknownFieldSet _unknownFields;
        private int _hasBits0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<ReverbEffect> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::DCL.ECSComponents.PBAudioSourceEffect.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ReverbEffect() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ReverbEffect(ReverbEffect other) : this() {
          _hasBits0 = other._hasBits0;
          preset_ = other.preset_;
          wetMix_ = other.wetMix_;
          decayTime_ = other.decayTime_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ReverbEffect Clone() {
          return new ReverbEffect(this);
        }

        /// <summary>Field number for the "preset" field.</summary>
        public const int PresetFieldNumber = 1;
        private global::DCL.ECSComponents.PBAudioSourceEffect.Types.ReverbPreset preset_;
        /// <summary>
        /// default: RP_ROOM. If wet_mix or decay_time is set, overrides preset.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::DCL.ECSComponents.PBAudioSourceEffect.Types.ReverbPreset Preset {
          get { if ((_hasBits0 & 1) != 0) { return preset_; } else { return global::DCL.ECSComponents.PBAudioSourceEffect.Types.ReverbPreset.RpRoom; } }
          set {
            _hasBits0 |= 1;
            preset_ = value;
          }
        }
        /// <summary>Gets whether the "preset" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasPreset {
          get { return (_hasBits0 & 1) != 0; }
        }
        /// <summary>Clears the value of the "preset" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearPreset() {
          _hasBits0 &= ~1;
        }

        /// <summary>Field number for the "wet_mix" field.</summary>
        public const int WetMixFieldNumber = 2;
        private float wetMix_;
        /// <summary>
        /// default: 0.3 (from preset), range [0.0, 1.0].
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float WetMix {
          get { if ((_hasBits0 & 2) != 0) { return wetMix_; } else { return 0F; } }
          set {
            _hasBits0 |= 2;
            wetMix_ = value;
          }
        }
        /// <summary>Gets whether the "wet_mix" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasWetMix {
          get { return (_hasBits0 & 2) != 0; }
        }
        /// <summary>Clears the value of the "wet_mix" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearWetMix() {
          _hasBits0 &= ~2;
        }

        /// <summary>Field number for the "decay_time" field.</summary>
        public const int DecayTimeFieldNumber = 3;
        private float decayTime_;
        /// <summary>
        /// Reverberation decay in seconds, default: 1.5 (from preset).
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float DecayTime {
          get { if ((_hasBits0 & 4) != 0) { return decayTime_; } else { return 0F; } }
          set {
            _hasBits0 |= 4;
            decayTime_ = value;
          }
        }
        /// <summary>Gets whether the "decay_time" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasDecayTime {
          get { return (_hasBits0 & 4) != 0; }
        }
        /// <summary>Clears the value of the "decay_time" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearDecayTime() {
          _hasBits0 &= ~4;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as ReverbEffect);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(ReverbEffect other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Preset != other.Preset) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(WetMix, other.WetMix)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(DecayTime, other.DecayTime)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (HasPreset) hash ^= Preset.GetHashCode();
          if (HasWetMix) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(WetMix);
          if (HasDecayTime) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(DecayTime);
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (HasPreset) {
            output.WriteRawTag(8);
            output.WriteEnum((int) Preset);
          }
          if (HasWetMix) {
            output.WriteRawTag(21);
            output.WriteFloat(WetMix);
          }
          if (HasDecayTime) {
            output.WriteRawTag(29);
            output.WriteFloat(DecayTime);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (HasPreset) {
            output.WriteRawTag(8);
            output.WriteEnum((int) Preset);
          }
          if (HasWetMix) {
            output.WriteRawTag(21);
            output.WriteFloat(WetMix);
          }
          if (HasDecayTime) {
            output.WriteRawTag(29);
            output.WriteFloat(DecayTime);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (HasPreset) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Preset);
          }
          if (HasWetMix) {
            size += 1 + 4;
          }
          if (HasDecayTime) {
            size += 1 + 4;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(ReverbEffect other) {
          if (other == null) {
            return;
          }
          if (other.HasPreset) {
            Preset = other.Preset;
          }
          if (other.HasWetMix) {
            WetMix = other.WetMix;
          }
          if (other.HasDecayTime) {
            DecayTime = other.DecayTime;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                Preset = (global::DCL.ECSComponents.PBAudioSourceEffect.Types.ReverbPreset) input.ReadEnum();
                break;
              }
              case 21: {
                WetMix = input.ReadFloat();
                break;
              }
              case 29: {
                DecayTime = input.ReadFloat();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                Preset = (global::DCL.ECSComponents.PBAudioSourceEffect.Types.ReverbPreset) input.ReadEnum();
                break;
              }
              case 21: {
                WetMix = input.ReadFloat();
                break;
              }
              case 29: {
                DecayTime = input.ReadFloat();
                break;
              }
            }
          }
        }
        #endif

      }

      /// <summary>
      /// Applies echo (delay) with configurable delay time and decay.
      /// </summary>
      public sealed partial class EchoEffect : pb::IMessage<EchoEffect>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<EchoEffect> _parser = new pb::MessageParser<EchoEffect>(() => new EchoEffect());
        private pb::UnknownFieldSet _unknownFields;
        private int _hasBits0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<EchoEffect> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::DCL.ECSComponents.PBAudioSourceEffect.Descriptor.NestedTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public EchoEffect() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public EchoEffect(EchoEffect other) : this() {
          _hasBits0 = other._hasBits0;
          delayMs_ = other.delayMs_;
          decay_ = other.decay_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public EchoEffect Clone() {
          return new EchoEffect(this);
        }

        /// <summary>Field number for the "delay_ms" field.</summary>
        public const int DelayMsFieldNumber = 1;
        private float delayMs_;
        /// <summary>
        /// default: 250.0, clamped to [10, 5000] on Explorer.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float DelayMs {
          get { if ((_hasBits0 & 1) != 0) { return delayMs_; } else { return 0F; } }
          set {
            _hasBits0 |= 1;
            delayMs_ = value;
          }
        }
        /// <summary>Gets whether the "delay_ms" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasDelayMs {
          get { return (_hasBits0 & 1) != 0; }
        }
        /// <summary>Clears the value of the "delay_ms" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearDelayMs() {
          _hasBits0 &= ~1;
        }

        /// <summary>Field number for the "decay" field.</summary>
        public const int DecayFieldNumber = 2;
        private float decay_;
        /// <summary>
        /// default: 0.5, clamped to [0.0, 1.0] on Explorer.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float Decay {
          get { if ((_hasBits0 & 2) != 0) { return decay_; } else { return 0F; } }
          set {
            _hasBits0 |= 2;
            decay_ = value;
          }
        }
        /// <summary>Gets whether the "decay" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasDecay {
          get { return (_hasBits0 & 2) != 0; }
        }
        /// <summary>Clears the value of the "decay" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearDecay() {
          _hasBits0 &= ~2;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as EchoEffect);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(EchoEffect other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(DelayMs, other.DelayMs)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Decay, other.Decay)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (HasDelayMs) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(DelayMs);
          if (HasDecay) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Decay);
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (HasDelayMs) {
            output.WriteRawTag(13);
            output.WriteFloat(DelayMs);
          }
          if (HasDecay) {
            output.WriteRawTag(21);
            output.WriteFloat(Decay);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (HasDelayMs) {
            output.WriteRawTag(13);
            output.WriteFloat(DelayMs);
          }
          if (HasDecay) {
            output.WriteRawTag(21);
            output.WriteFloat(Decay);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (HasDelayMs) {
            size += 1 + 4;
          }
          if (HasDecay) {
            size += 1 + 4;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(EchoEffect other) {
          if (other == null) {
            return;
          }
          if (other.HasDelayMs) {
            DelayMs = other.DelayMs;
          }
          if (other.HasDecay) {
            Decay = other.Decay;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 13: {
                DelayMs = input.ReadFloat();
                break;
              }
              case 21: {
                Decay = input.ReadFloat();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 13: {
                DelayMs = input.ReadFloat();
                break;
              }
              case 21: {
                Decay = input.ReadFloat();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
