// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: decentraland/sdk/components/avatar_freeze_movement.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DCL.ECSComponents {

  /// <summary>Holder for reflection information generated from decentraland/sdk/components/avatar_freeze_movement.proto</summary>
  public static partial class AvatarFreezeMovementReflection {

    #region Descriptor
    /// <summary>File descriptor for decentraland/sdk/components/avatar_freeze_movement.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AvatarFreezeMovementReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjhkZWNlbnRyYWxhbmQvc2RrL2NvbXBvbmVudHMvYXZhdGFyX2ZyZWV6ZV9t",
            "b3ZlbWVudC5wcm90bxIbZGVjZW50cmFsYW5kLnNkay5jb21wb25lbnRzIkIK",
            "FlBCQXZhdGFyRnJlZXplTW92ZW1lbnQSGAoLZnJlZXplX21hc2sYASABKA1I",
            "AIgBAUIOCgxfZnJlZXplX21hc2sqhAEKGEF2YXRhckZyZWV6ZU1vdmVtZW50",
            "VHlwZRINCglBRk1UX05PTkUQABIMCghBRk1UX0FMTBABEg0KCUFGTVRfV0FM",
            "SxACEgwKCEFGTVRfUlVOEAQSDQoJQUZNVF9KVU1QEAgSDgoKQUZNVF9FTU9U",
            "RRAQEg8KC0FGTVRfQ0FNRVJBECBCFKoCEURDTC5FQ1NDb21wb25lbnRzYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DCL.ECSComponents.AvatarFreezeMovementType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DCL.ECSComponents.PBAvatarFreezeMovement), global::DCL.ECSComponents.PBAvatarFreezeMovement.Parser, new[]{ "FreezeMask" }, new[]{ "FreezeMask" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// AvatarFreezeMovementType determines the movement to freeze and it can be used in bit flag form.
  /// </summary>
  public enum AvatarFreezeMovementType {
    [pbr::OriginalName("AFMT_NONE")] AfmtNone = 0,
    [pbr::OriginalName("AFMT_ALL")] AfmtAll = 1,
    [pbr::OriginalName("AFMT_WALK")] AfmtWalk = 2,
    [pbr::OriginalName("AFMT_RUN")] AfmtRun = 4,
    [pbr::OriginalName("AFMT_JUMP")] AfmtJump = 8,
    [pbr::OriginalName("AFMT_EMOTE")] AfmtEmote = 16,
    [pbr::OriginalName("AFMT_CAMERA")] AfmtCamera = 32,
  }

  #endregion

  #region Messages
  /// <summary>
  /// TODO: add description
  /// </summary>
  public sealed partial class PBAvatarFreezeMovement : pb::IMessage<PBAvatarFreezeMovement>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PBAvatarFreezeMovement> _parser = new pb::MessageParser<PBAvatarFreezeMovement>(() => new PBAvatarFreezeMovement());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PBAvatarFreezeMovement> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DCL.ECSComponents.AvatarFreezeMovementReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBAvatarFreezeMovement() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBAvatarFreezeMovement(PBAvatarFreezeMovement other) : this() {
      _hasBits0 = other._hasBits0;
      freezeMask_ = other.freezeMask_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBAvatarFreezeMovement Clone() {
      return new PBAvatarFreezeMovement(this);
    }

    /// <summary>Field number for the "freeze_mask" field.</summary>
    public const int FreezeMaskFieldNumber = 1;
    private uint freezeMask_;
    /// <summary>
    /// disabled AvatarFreezeMovementType (default AFMT_ALL)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FreezeMask {
      get { if ((_hasBits0 & 1) != 0) { return freezeMask_; } else { return 0; } }
      set {
        _hasBits0 |= 1;
        freezeMask_ = value;
      }
    }
    /// <summary>Gets whether the "freeze_mask" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFreezeMask {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "freeze_mask" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFreezeMask() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PBAvatarFreezeMovement);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PBAvatarFreezeMovement other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FreezeMask != other.FreezeMask) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasFreezeMask) hash ^= FreezeMask.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasFreezeMask) {
        output.WriteRawTag(8);
        output.WriteUInt32(FreezeMask);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasFreezeMask) {
        output.WriteRawTag(8);
        output.WriteUInt32(FreezeMask);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasFreezeMask) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FreezeMask);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PBAvatarFreezeMovement other) {
      if (other == null) {
        return;
      }
      if (other.HasFreezeMask) {
        FreezeMask = other.FreezeMask;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            FreezeMask = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            FreezeMask = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
