// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: decentraland/sdk/components/billboard.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DCL.ECSComponents {

  /// <summary>Holder for reflection information generated from decentraland/sdk/components/billboard.proto</summary>
  public static partial class BillboardReflection {

    #region Descriptor
    /// <summary>File descriptor for decentraland/sdk/components/billboard.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BillboardReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CitkZWNlbnRyYWxhbmQvc2RrL2NvbXBvbmVudHMvYmlsbGJvYXJkLnByb3Rv",
            "EhtkZWNlbnRyYWxhbmQuc2RrLmNvbXBvbmVudHMilwEKC1BCQmlsbGJvYXJk",
            "EkcKDmJpbGxib2FyZF9tb2RlGAEgASgOMiouZGVjZW50cmFsYW5kLnNkay5j",
            "b21wb25lbnRzLkJpbGxib2FyZE1vZGVIAIgBARIaCg10YXJnZXRfZW50aXR5",
            "GAIgASgNSAGIAQFCEQoPX2JpbGxib2FyZF9tb2RlQhAKDl90YXJnZXRfZW50",
            "aXR5KkYKDUJpbGxib2FyZE1vZGUSCwoHQk1fTk9ORRAAEggKBEJNX1gQARII",
            "CgRCTV9ZEAISCAoEQk1fWhAEEgoKBkJNX0FMTBAHQhSqAhFEQ0wuRUNTQ29t",
            "cG9uZW50c2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DCL.ECSComponents.BillboardMode), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DCL.ECSComponents.PBBillboard), global::DCL.ECSComponents.PBBillboard.Parser, new[]{ "BillboardMode", "TargetEntity" }, new[]{ "BillboardMode", "TargetEntity" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// BillboardMode indicates one or more axis for automatic rotation, in OR-able bit flag form.
  /// Only the values below and the (BM_X | BM_Y) combination are valid.
  /// </summary>
  public enum BillboardMode {
    [pbr::OriginalName("BM_NONE")] BmNone = 0,
    [pbr::OriginalName("BM_X")] BmX = 1,
    [pbr::OriginalName("BM_Y")] BmY = 2,
    [pbr::OriginalName("BM_Z")] BmZ = 4,
    /// <summary>
    /// bitwise combination BM_X | BM_Y | BM_Z
    /// </summary>
    [pbr::OriginalName("BM_ALL")] BmAll = 7,
  }

  #endregion

  #region Messages
  /// <summary>
  /// The Billboard component makes an Entity automatically reorient its rotation to face a target.
  /// By default (when target_entity is unset), the billboard faces the main camera. When target_entity
  /// is set, the billboard faces that entity instead. Setting target_entity to the camera reserved
  /// entity (2) is equivalent to leaving the field unset. If the referenced target entity doesn’t exist
  /// or is deleted, the billboard reorientation is disabled until the target exists again.
  ///
  /// As the name indicates, it’s used to display in-game billboards and frequently combined with
  /// the TextShape component.
  ///
  /// Billboard only affects the Entity’s rotation. Its scale and position are still determined by its
  /// Transform.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PBBillboard : pb::IMessage<PBBillboard>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PBBillboard> _parser = new pb::MessageParser<PBBillboard>(() => new PBBillboard());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PBBillboard> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DCL.ECSComponents.BillboardReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBBillboard() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBBillboard(PBBillboard other) : this() {
      _hasBits0 = other._hasBits0;
      billboardMode_ = other.billboardMode_;
      targetEntity_ = other.targetEntity_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBBillboard Clone() {
      return new PBBillboard(this);
    }

    /// <summary>Field number for the "billboard_mode" field.</summary>
    public const int BillboardModeFieldNumber = 1;
    private readonly static global::DCL.ECSComponents.BillboardMode BillboardModeDefaultValue = global::DCL.ECSComponents.BillboardMode.BmNone;

    private global::DCL.ECSComponents.BillboardMode billboardMode_;
    /// <summary>
    /// the BillboardMode (default: BM_ALL)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DCL.ECSComponents.BillboardMode BillboardMode {
      get { if ((_hasBits0 & 1) != 0) { return billboardMode_; } else { return BillboardModeDefaultValue; } }
      set {
        _hasBits0 |= 1;
        billboardMode_ = value;
      }
    }
    /// <summary>Gets whether the "billboard_mode" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasBillboardMode {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "billboard_mode" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBillboardMode() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "target_entity" field.</summary>
    public const int TargetEntityFieldNumber = 2;
    private readonly static uint TargetEntityDefaultValue = 0;

    private uint targetEntity_;
    /// <summary>
    /// entity to face instead of the camera; if the referenced entity doesn’t exist, the billboard behavior is disabled until it does
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TargetEntity {
      get { if ((_hasBits0 & 2) != 0) { return targetEntity_; } else { return TargetEntityDefaultValue; } }
      set {
        _hasBits0 |= 2;
        targetEntity_ = value;
      }
    }
    /// <summary>Gets whether the "target_entity" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTargetEntity {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "target_entity" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTargetEntity() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PBBillboard);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PBBillboard other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BillboardMode != other.BillboardMode) return false;
      if (TargetEntity != other.TargetEntity) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasBillboardMode) hash ^= BillboardMode.GetHashCode();
      if (HasTargetEntity) hash ^= TargetEntity.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasBillboardMode) {
        output.WriteRawTag(8);
        output.WriteEnum((int) BillboardMode);
      }
      if (HasTargetEntity) {
        output.WriteRawTag(16);
        output.WriteUInt32(TargetEntity);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasBillboardMode) {
        output.WriteRawTag(8);
        output.WriteEnum((int) BillboardMode);
      }
      if (HasTargetEntity) {
        output.WriteRawTag(16);
        output.WriteUInt32(TargetEntity);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasBillboardMode) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) BillboardMode);
      }
      if (HasTargetEntity) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TargetEntity);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PBBillboard other) {
      if (other == null) {
        return;
      }
      if (other.HasBillboardMode) {
        BillboardMode = other.BillboardMode;
      }
      if (other.HasTargetEntity) {
        TargetEntity = other.TargetEntity;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            BillboardMode = (global::DCL.ECSComponents.BillboardMode) input.ReadEnum();
            break;
          }
          case 16: {
            TargetEntity = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            BillboardMode = (global::DCL.ECSComponents.BillboardMode) input.ReadEnum();
            break;
          }
          case 16: {
            TargetEntity = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
