// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: decentraland/sdk/components/light_source.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DCL.ECSComponents {

  /// <summary>Holder for reflection information generated from decentraland/sdk/components/light_source.proto</summary>
  public static partial class LightSourceReflection {

    #region Descriptor
    /// <summary>File descriptor for decentraland/sdk/components/light_source.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LightSourceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci5kZWNlbnRyYWxhbmQvc2RrL2NvbXBvbmVudHMvbGlnaHRfc291cmNlLnBy",
            "b3RvEhtkZWNlbnRyYWxhbmQuc2RrLmNvbXBvbmVudHMaIGRlY2VudHJhbGFu",
            "ZC9jb21tb24vY29sb3JzLnByb3RvGiFkZWNlbnRyYWxhbmQvY29tbW9uL3Rl",
            "eHR1cmUucHJvdG8i4gUKDVBCTGlnaHRTb3VyY2USEwoGYWN0aXZlGAQgASgI",
            "SAGIAQESLwoFY29sb3IYASABKAsyGy5kZWNlbnRyYWxhbmQuY29tbW9uLkNv",
            "bG9yM0gCiAEBEhcKCmJyaWdodG5lc3MYAiABKAJIA4gBARISCgVyYW5nZRgD",
            "IAEoAkgEiAEBEkEKBXBvaW50GAYgASgLMjAuZGVjZW50cmFsYW5kLnNkay5j",
            "b21wb25lbnRzLlBCTGlnaHRTb3VyY2UuUG9pbnRIABI/CgRzcG90GAcgASgL",
            "Mi8uZGVjZW50cmFsYW5kLnNkay5jb21wb25lbnRzLlBCTGlnaHRTb3VyY2Uu",
            "U3BvdEgAGl4KBVBvaW50EkoKBnNoYWRvdxgFIAEoDjI1LmRlY2VudHJhbGFu",
            "ZC5zZGsuY29tcG9uZW50cy5QQkxpZ2h0U291cmNlLlNoYWRvd1R5cGVIAIgB",
            "AUIJCgdfc2hhZG93Go4CCgRTcG90EhgKC2lubmVyX2FuZ2xlGAEgASgCSACI",
            "AQESGAoLb3V0ZXJfYW5nbGUYAiABKAJIAYgBARJKCgZzaGFkb3cYBSABKA4y",
            "NS5kZWNlbnRyYWxhbmQuc2RrLmNvbXBvbmVudHMuUEJMaWdodFNvdXJjZS5T",
            "aGFkb3dUeXBlSAKIAQESQwoTc2hhZG93X21hc2tfdGV4dHVyZRgIIAEoCzIh",
            "LmRlY2VudHJhbGFuZC5jb21tb24uVGV4dHVyZVVuaW9uSAOIAQFCDgoMX2lu",
            "bmVyX2FuZ2xlQg4KDF9vdXRlcl9hbmdsZUIJCgdfc2hhZG93QhYKFF9zaGFk",
            "b3dfbWFza190ZXh0dXJlIjMKClNoYWRvd1R5cGUSCwoHU1RfTk9ORRAAEgsK",
            "B1NUX1NPRlQQARILCgdTVF9IQVJEEAJCBgoEdHlwZUIJCgdfYWN0aXZlQggK",
            "Bl9jb2xvckINCgtfYnJpZ2h0bmVzc0IICgZfcmFuZ2VCFKoCEURDTC5FQ1ND",
            "b21wb25lbnRzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Decentraland.Common.ColorsReflection.Descriptor, global::Decentraland.Common.TextureReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DCL.ECSComponents.PBLightSource), global::DCL.ECSComponents.PBLightSource.Parser, new[]{ "Active", "Color", "Brightness", "Range", "Point", "Spot" }, new[]{ "Type", "Active", "Color", "Brightness", "Range" }, new[]{ typeof(global::DCL.ECSComponents.PBLightSource.Types.ShadowType) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::DCL.ECSComponents.PBLightSource.Types.Point), global::DCL.ECSComponents.PBLightSource.Types.Point.Parser, new[]{ "Shadow" }, new[]{ "Shadow" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DCL.ECSComponents.PBLightSource.Types.Spot), global::DCL.ECSComponents.PBLightSource.Types.Spot.Parser, new[]{ "InnerAngle", "OuterAngle", "Shadow", "ShadowMaskTexture" }, new[]{ "InnerAngle", "OuterAngle", "Shadow", "ShadowMaskTexture" }, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PBLightSource : pb::IMessage<PBLightSource>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PBLightSource> _parser = new pb::MessageParser<PBLightSource>(() => new PBLightSource());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PBLightSource> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DCL.ECSComponents.LightSourceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBLightSource() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBLightSource(PBLightSource other) : this() {
      _hasBits0 = other._hasBits0;
      active_ = other.active_;
      color_ = other.color_ != null ? other.color_.Clone() : null;
      brightness_ = other.brightness_;
      range_ = other.range_;
      switch (other.TypeCase) {
        case TypeOneofCase.Point:
          Point = other.Point.Clone();
          break;
        case TypeOneofCase.Spot:
          Spot = other.Spot.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBLightSource Clone() {
      return new PBLightSource(this);
    }

    /// <summary>Field number for the "active" field.</summary>
    public const int ActiveFieldNumber = 4;
    private bool active_;
    /// <summary>
    /// default = true, whether the lightSource is active or not.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Active {
      get { if ((_hasBits0 & 4) != 0) { return active_; } else { return false; } }
      set {
        _hasBits0 |= 4;
        active_ = value;
      }
    }
    /// <summary>Gets whether the "active" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasActive {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "active" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearActive() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "color" field.</summary>
    public const int ColorFieldNumber = 1;
    private global::Decentraland.Common.Color3 color_;
    /// <summary>
    /// default = Color.white, the tint of the light, in RGB format where each component is a floating point value with a range from 0 to 1.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Decentraland.Common.Color3 Color {
      get { return color_; }
      set {
        color_ = value;
      }
    }

    /// <summary>Field number for the "brightness" field.</summary>
    public const int BrightnessFieldNumber = 2;
    private float brightness_;
    /// <summary>
    /// default = 250, ranges from 1 (dim) to 100,000 (very bright), expressed in Lumens for Point and Spot.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Brightness {
      get { if ((_hasBits0 & 1) != 0) { return brightness_; } else { return 0F; } }
      set {
        _hasBits0 |= 1;
        brightness_ = value;
      }
    }
    /// <summary>Gets whether the "brightness" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasBrightness {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "brightness" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBrightness() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "range" field.</summary>
    public const int RangeFieldNumber = 3;
    private float range_;
    /// <summary>
    /// default = 10, how far the light travels, expressed in meters.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Range {
      get { if ((_hasBits0 & 2) != 0) { return range_; } else { return 0F; } }
      set {
        _hasBits0 |= 2;
        range_ = value;
      }
    }
    /// <summary>Gets whether the "range" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRange {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "range" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRange() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "point" field.</summary>
    public const int PointFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DCL.ECSComponents.PBLightSource.Types.Point Point {
      get { return typeCase_ == TypeOneofCase.Point ? (global::DCL.ECSComponents.PBLightSource.Types.Point) type_ : null; }
      set {
        type_ = value;
        typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.Point;
      }
    }

    /// <summary>Field number for the "spot" field.</summary>
    public const int SpotFieldNumber = 7;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DCL.ECSComponents.PBLightSource.Types.Spot Spot {
      get { return typeCase_ == TypeOneofCase.Spot ? (global::DCL.ECSComponents.PBLightSource.Types.Spot) type_ : null; }
      set {
        type_ = value;
        typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.Spot;
      }
    }

    private object type_;
    /// <summary>Enum of possible cases for the "type" oneof.</summary>
    public enum TypeOneofCase {
      None = 0,
      Point = 6,
      Spot = 7,
    }
    private TypeOneofCase typeCase_ = TypeOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TypeOneofCase TypeCase {
      get { return typeCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearType() {
      typeCase_ = TypeOneofCase.None;
      type_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PBLightSource);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PBLightSource other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Active != other.Active) return false;
      if (!object.Equals(Color, other.Color)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Brightness, other.Brightness)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Range, other.Range)) return false;
      if (!object.Equals(Point, other.Point)) return false;
      if (!object.Equals(Spot, other.Spot)) return false;
      if (TypeCase != other.TypeCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasActive) hash ^= Active.GetHashCode();
      if (color_ != null) hash ^= Color.GetHashCode();
      if (HasBrightness) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Brightness);
      if (HasRange) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Range);
      if (typeCase_ == TypeOneofCase.Point) hash ^= Point.GetHashCode();
      if (typeCase_ == TypeOneofCase.Spot) hash ^= Spot.GetHashCode();
      hash ^= (int) typeCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (color_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Color);
      }
      if (HasBrightness) {
        output.WriteRawTag(21);
        output.WriteFloat(Brightness);
      }
      if (HasRange) {
        output.WriteRawTag(29);
        output.WriteFloat(Range);
      }
      if (HasActive) {
        output.WriteRawTag(32);
        output.WriteBool(Active);
      }
      if (typeCase_ == TypeOneofCase.Point) {
        output.WriteRawTag(50);
        output.WriteMessage(Point);
      }
      if (typeCase_ == TypeOneofCase.Spot) {
        output.WriteRawTag(58);
        output.WriteMessage(Spot);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (color_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Color);
      }
      if (HasBrightness) {
        output.WriteRawTag(21);
        output.WriteFloat(Brightness);
      }
      if (HasRange) {
        output.WriteRawTag(29);
        output.WriteFloat(Range);
      }
      if (HasActive) {
        output.WriteRawTag(32);
        output.WriteBool(Active);
      }
      if (typeCase_ == TypeOneofCase.Point) {
        output.WriteRawTag(50);
        output.WriteMessage(Point);
      }
      if (typeCase_ == TypeOneofCase.Spot) {
        output.WriteRawTag(58);
        output.WriteMessage(Spot);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasActive) {
        size += 1 + 1;
      }
      if (color_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Color);
      }
      if (HasBrightness) {
        size += 1 + 4;
      }
      if (HasRange) {
        size += 1 + 4;
      }
      if (typeCase_ == TypeOneofCase.Point) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Point);
      }
      if (typeCase_ == TypeOneofCase.Spot) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Spot);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PBLightSource other) {
      if (other == null) {
        return;
      }
      if (other.HasActive) {
        Active = other.Active;
      }
      if (other.color_ != null) {
        if (color_ == null) {
          Color = new global::Decentraland.Common.Color3();
        }
        Color.MergeFrom(other.Color);
      }
      if (other.HasBrightness) {
        Brightness = other.Brightness;
      }
      if (other.HasRange) {
        Range = other.Range;
      }
      switch (other.TypeCase) {
        case TypeOneofCase.Point:
          if (Point == null) {
            Point = new global::DCL.ECSComponents.PBLightSource.Types.Point();
          }
          Point.MergeFrom(other.Point);
          break;
        case TypeOneofCase.Spot:
          if (Spot == null) {
            Spot = new global::DCL.ECSComponents.PBLightSource.Types.Spot();
          }
          Spot.MergeFrom(other.Spot);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (color_ == null) {
              Color = new global::Decentraland.Common.Color3();
            }
            input.ReadMessage(Color);
            break;
          }
          case 21: {
            Brightness = input.ReadFloat();
            break;
          }
          case 29: {
            Range = input.ReadFloat();
            break;
          }
          case 32: {
            Active = input.ReadBool();
            break;
          }
          case 50: {
            global::DCL.ECSComponents.PBLightSource.Types.Point subBuilder = new global::DCL.ECSComponents.PBLightSource.Types.Point();
            if (typeCase_ == TypeOneofCase.Point) {
              subBuilder.MergeFrom(Point);
            }
            input.ReadMessage(subBuilder);
            Point = subBuilder;
            break;
          }
          case 58: {
            global::DCL.ECSComponents.PBLightSource.Types.Spot subBuilder = new global::DCL.ECSComponents.PBLightSource.Types.Spot();
            if (typeCase_ == TypeOneofCase.Spot) {
              subBuilder.MergeFrom(Spot);
            }
            input.ReadMessage(subBuilder);
            Spot = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (color_ == null) {
              Color = new global::Decentraland.Common.Color3();
            }
            input.ReadMessage(Color);
            break;
          }
          case 21: {
            Brightness = input.ReadFloat();
            break;
          }
          case 29: {
            Range = input.ReadFloat();
            break;
          }
          case 32: {
            Active = input.ReadBool();
            break;
          }
          case 50: {
            global::DCL.ECSComponents.PBLightSource.Types.Point subBuilder = new global::DCL.ECSComponents.PBLightSource.Types.Point();
            if (typeCase_ == TypeOneofCase.Point) {
              subBuilder.MergeFrom(Point);
            }
            input.ReadMessage(subBuilder);
            Point = subBuilder;
            break;
          }
          case 58: {
            global::DCL.ECSComponents.PBLightSource.Types.Spot subBuilder = new global::DCL.ECSComponents.PBLightSource.Types.Spot();
            if (typeCase_ == TypeOneofCase.Spot) {
              subBuilder.MergeFrom(Spot);
            }
            input.ReadMessage(subBuilder);
            Spot = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the PBLightSource message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum ShadowType {
        /// <summary>
        /// No shadows are cast from this LightSource.
        /// </summary>
        [pbr::OriginalName("ST_NONE")] StNone = 0,
        /// <summary>
        /// More realistic type of shadow that reduces block artifacts, noise or pixelation, but requires more processing.
        /// </summary>
        [pbr::OriginalName("ST_SOFT")] StSoft = 1,
        /// <summary>
        /// Less realistic type of shadow but more performant, uses hard edges.
        /// </summary>
        [pbr::OriginalName("ST_HARD")] StHard = 2,
      }

      public sealed partial class Point : pb::IMessage<Point>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Point> _parser = new pb::MessageParser<Point>(() => new Point());
        private pb::UnknownFieldSet _unknownFields;
        private int _hasBits0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Point> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::DCL.ECSComponents.PBLightSource.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Point() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Point(Point other) : this() {
          _hasBits0 = other._hasBits0;
          shadow_ = other.shadow_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Point Clone() {
          return new Point(this);
        }

        /// <summary>Field number for the "shadow" field.</summary>
        public const int ShadowFieldNumber = 5;
        private global::DCL.ECSComponents.PBLightSource.Types.ShadowType shadow_;
        /// <summary>
        /// default = ShadowType.ST_NONE The type of shadow the light source supports.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::DCL.ECSComponents.PBLightSource.Types.ShadowType Shadow {
          get { if ((_hasBits0 & 1) != 0) { return shadow_; } else { return global::DCL.ECSComponents.PBLightSource.Types.ShadowType.StNone; } }
          set {
            _hasBits0 |= 1;
            shadow_ = value;
          }
        }
        /// <summary>Gets whether the "shadow" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasShadow {
          get { return (_hasBits0 & 1) != 0; }
        }
        /// <summary>Clears the value of the "shadow" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearShadow() {
          _hasBits0 &= ~1;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Point);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Point other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Shadow != other.Shadow) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (HasShadow) hash ^= Shadow.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (HasShadow) {
            output.WriteRawTag(40);
            output.WriteEnum((int) Shadow);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (HasShadow) {
            output.WriteRawTag(40);
            output.WriteEnum((int) Shadow);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (HasShadow) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Shadow);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Point other) {
          if (other == null) {
            return;
          }
          if (other.HasShadow) {
            Shadow = other.Shadow;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 40: {
                Shadow = (global::DCL.ECSComponents.PBLightSource.Types.ShadowType) input.ReadEnum();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 40: {
                Shadow = (global::DCL.ECSComponents.PBLightSource.Types.ShadowType) input.ReadEnum();
                break;
              }
            }
          }
        }
        #endif

      }

      public sealed partial class Spot : pb::IMessage<Spot>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Spot> _parser = new pb::MessageParser<Spot>(() => new Spot());
        private pb::UnknownFieldSet _unknownFields;
        private int _hasBits0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Spot> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::DCL.ECSComponents.PBLightSource.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Spot() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Spot(Spot other) : this() {
          _hasBits0 = other._hasBits0;
          innerAngle_ = other.innerAngle_;
          outerAngle_ = other.outerAngle_;
          shadow_ = other.shadow_;
          shadowMaskTexture_ = other.shadowMaskTexture_ != null ? other.shadowMaskTexture_.Clone() : null;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Spot Clone() {
          return new Spot(this);
        }

        /// <summary>Field number for the "inner_angle" field.</summary>
        public const int InnerAngleFieldNumber = 1;
        private float innerAngle_;
        /// <summary>
        /// default = 21.8. Inner angle can't be higher than outer angle, otherwise will default to same value. Min value is 0. Max value is 179.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float InnerAngle {
          get { if ((_hasBits0 & 1) != 0) { return innerAngle_; } else { return 0F; } }
          set {
            _hasBits0 |= 1;
            innerAngle_ = value;
          }
        }
        /// <summary>Gets whether the "inner_angle" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasInnerAngle {
          get { return (_hasBits0 & 1) != 0; }
        }
        /// <summary>Clears the value of the "inner_angle" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearInnerAngle() {
          _hasBits0 &= ~1;
        }

        /// <summary>Field number for the "outer_angle" field.</summary>
        public const int OuterAngleFieldNumber = 2;
        private float outerAngle_;
        /// <summary>
        /// default = 30. Outer angle can't be lower than inner angle, otherwise will inner angle will be set to same value. Max value is 179.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float OuterAngle {
          get { if ((_hasBits0 & 2) != 0) { return outerAngle_; } else { return 0F; } }
          set {
            _hasBits0 |= 2;
            outerAngle_ = value;
          }
        }
        /// <summary>Gets whether the "outer_angle" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasOuterAngle {
          get { return (_hasBits0 & 2) != 0; }
        }
        /// <summary>Clears the value of the "outer_angle" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearOuterAngle() {
          _hasBits0 &= ~2;
        }

        /// <summary>Field number for the "shadow" field.</summary>
        public const int ShadowFieldNumber = 5;
        private global::DCL.ECSComponents.PBLightSource.Types.ShadowType shadow_;
        /// <summary>
        /// default = ShadowType.ST_NONE The type of shadow the light source supports.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::DCL.ECSComponents.PBLightSource.Types.ShadowType Shadow {
          get { if ((_hasBits0 & 4) != 0) { return shadow_; } else { return global::DCL.ECSComponents.PBLightSource.Types.ShadowType.StNone; } }
          set {
            _hasBits0 |= 4;
            shadow_ = value;
          }
        }
        /// <summary>Gets whether the "shadow" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasShadow {
          get { return (_hasBits0 & 4) != 0; }
        }
        /// <summary>Clears the value of the "shadow" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearShadow() {
          _hasBits0 &= ~4;
        }

        /// <summary>Field number for the "shadow_mask_texture" field.</summary>
        public const int ShadowMaskTextureFieldNumber = 8;
        private global::Decentraland.Common.TextureUnion shadowMaskTexture_;
        /// <summary>
        /// Texture mask through which shadows are cast to simulate caustics, soft shadows, and light shapes such as light entering from a window.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Decentraland.Common.TextureUnion ShadowMaskTexture {
          get { return shadowMaskTexture_; }
          set {
            shadowMaskTexture_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Spot);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Spot other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(InnerAngle, other.InnerAngle)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(OuterAngle, other.OuterAngle)) return false;
          if (Shadow != other.Shadow) return false;
          if (!object.Equals(ShadowMaskTexture, other.ShadowMaskTexture)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (HasInnerAngle) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(InnerAngle);
          if (HasOuterAngle) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(OuterAngle);
          if (HasShadow) hash ^= Shadow.GetHashCode();
          if (shadowMaskTexture_ != null) hash ^= ShadowMaskTexture.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (HasInnerAngle) {
            output.WriteRawTag(13);
            output.WriteFloat(InnerAngle);
          }
          if (HasOuterAngle) {
            output.WriteRawTag(21);
            output.WriteFloat(OuterAngle);
          }
          if (HasShadow) {
            output.WriteRawTag(40);
            output.WriteEnum((int) Shadow);
          }
          if (shadowMaskTexture_ != null) {
            output.WriteRawTag(66);
            output.WriteMessage(ShadowMaskTexture);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (HasInnerAngle) {
            output.WriteRawTag(13);
            output.WriteFloat(InnerAngle);
          }
          if (HasOuterAngle) {
            output.WriteRawTag(21);
            output.WriteFloat(OuterAngle);
          }
          if (HasShadow) {
            output.WriteRawTag(40);
            output.WriteEnum((int) Shadow);
          }
          if (shadowMaskTexture_ != null) {
            output.WriteRawTag(66);
            output.WriteMessage(ShadowMaskTexture);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (HasInnerAngle) {
            size += 1 + 4;
          }
          if (HasOuterAngle) {
            size += 1 + 4;
          }
          if (HasShadow) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Shadow);
          }
          if (shadowMaskTexture_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(ShadowMaskTexture);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Spot other) {
          if (other == null) {
            return;
          }
          if (other.HasInnerAngle) {
            InnerAngle = other.InnerAngle;
          }
          if (other.HasOuterAngle) {
            OuterAngle = other.OuterAngle;
          }
          if (other.HasShadow) {
            Shadow = other.Shadow;
          }
          if (other.shadowMaskTexture_ != null) {
            if (shadowMaskTexture_ == null) {
              ShadowMaskTexture = new global::Decentraland.Common.TextureUnion();
            }
            ShadowMaskTexture.MergeFrom(other.ShadowMaskTexture);
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 13: {
                InnerAngle = input.ReadFloat();
                break;
              }
              case 21: {
                OuterAngle = input.ReadFloat();
                break;
              }
              case 40: {
                Shadow = (global::DCL.ECSComponents.PBLightSource.Types.ShadowType) input.ReadEnum();
                break;
              }
              case 66: {
                if (shadowMaskTexture_ == null) {
                  ShadowMaskTexture = new global::Decentraland.Common.TextureUnion();
                }
                input.ReadMessage(ShadowMaskTexture);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 13: {
                InnerAngle = input.ReadFloat();
                break;
              }
              case 21: {
                OuterAngle = input.ReadFloat();
                break;
              }
              case 40: {
                Shadow = (global::DCL.ECSComponents.PBLightSource.Types.ShadowType) input.ReadEnum();
                break;
              }
              case 66: {
                if (shadowMaskTexture_ == null) {
                  ShadowMaskTexture = new global::Decentraland.Common.TextureUnion();
                }
                input.ReadMessage(ShadowMaskTexture);
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
