// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: decentraland/sdk/components/player_input_movement.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DCL.ECSComponents {

  /// <summary>Holder for reflection information generated from decentraland/sdk/components/player_input_movement.proto</summary>
  public static partial class PlayerInputMovementReflection {

    #region Descriptor
    /// <summary>File descriptor for decentraland/sdk/components/player_input_movement.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlayerInputMovementReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjdkZWNlbnRyYWxhbmQvc2RrL2NvbXBvbmVudHMvcGxheWVyX2lucHV0X21v",
            "dmVtZW50LnByb3RvEhtkZWNlbnRyYWxhbmQuc2RrLmNvbXBvbmVudHMikgIK",
            "FVBCUGxheWVySW5wdXRNb3ZlbWVudBJXCghzdGFuZGFyZBgBIAEoCzJDLmRl",
            "Y2VudHJhbGFuZC5zZGsuY29tcG9uZW50cy5QQlBsYXllcklucHV0TW92ZW1l",
            "bnQuU3RhbmRhcmRNb3ZlbWVudEgAGpcBChBTdGFuZGFyZE1vdmVtZW50EhMK",
            "C2Rpc2FibGVfYWxsGAEgASgIEhQKDGRpc2FibGVfd2FsaxgCIAEoCBITCgtk",
            "aXNhYmxlX3J1bhgDIAEoCBIUCgxkaXNhYmxlX2p1bXAYBCABKAgSFQoNZGlz",
            "YWJsZV9lbW90ZRgFIAEoCBIWCg5kaXNhYmxlX2NhbWVyYRgGIAEoCEIGCgRt",
            "b2RlQhSqAhFEQ0wuRUNTQ29tcG9uZW50c2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DCL.ECSComponents.PBPlayerInputMovement), global::DCL.ECSComponents.PBPlayerInputMovement.Parser, new[]{ "Standard" }, new[]{ "Mode" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::DCL.ECSComponents.PBPlayerInputMovement.Types.StandardMovement), global::DCL.ECSComponents.PBPlayerInputMovement.Types.StandardMovement.Parser, new[]{ "DisableAll", "DisableWalk", "DisableRun", "DisableJump", "DisableEmote", "DisableCamera" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PBPlayerInputMovement : pb::IMessage<PBPlayerInputMovement>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PBPlayerInputMovement> _parser = new pb::MessageParser<PBPlayerInputMovement>(() => new PBPlayerInputMovement());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PBPlayerInputMovement> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DCL.ECSComponents.PlayerInputMovementReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBPlayerInputMovement() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBPlayerInputMovement(PBPlayerInputMovement other) : this() {
      switch (other.ModeCase) {
        case ModeOneofCase.Standard:
          Standard = other.Standard.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBPlayerInputMovement Clone() {
      return new PBPlayerInputMovement(this);
    }

    /// <summary>Field number for the "standard" field.</summary>
    public const int StandardFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DCL.ECSComponents.PBPlayerInputMovement.Types.StandardMovement Standard {
      get { return modeCase_ == ModeOneofCase.Standard ? (global::DCL.ECSComponents.PBPlayerInputMovement.Types.StandardMovement) mode_ : null; }
      set {
        mode_ = value;
        modeCase_ = value == null ? ModeOneofCase.None : ModeOneofCase.Standard;
      }
    }

    private object mode_;
    /// <summary>Enum of possible cases for the "mode" oneof.</summary>
    public enum ModeOneofCase {
      None = 0,
      Standard = 1,
    }
    private ModeOneofCase modeCase_ = ModeOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ModeOneofCase ModeCase {
      get { return modeCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMode() {
      modeCase_ = ModeOneofCase.None;
      mode_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PBPlayerInputMovement);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PBPlayerInputMovement other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Standard, other.Standard)) return false;
      if (ModeCase != other.ModeCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (modeCase_ == ModeOneofCase.Standard) hash ^= Standard.GetHashCode();
      hash ^= (int) modeCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (modeCase_ == ModeOneofCase.Standard) {
        output.WriteRawTag(10);
        output.WriteMessage(Standard);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (modeCase_ == ModeOneofCase.Standard) {
        output.WriteRawTag(10);
        output.WriteMessage(Standard);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (modeCase_ == ModeOneofCase.Standard) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Standard);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PBPlayerInputMovement other) {
      if (other == null) {
        return;
      }
      switch (other.ModeCase) {
        case ModeOneofCase.Standard:
          if (Standard == null) {
            Standard = new global::DCL.ECSComponents.PBPlayerInputMovement.Types.StandardMovement();
          }
          Standard.MergeFrom(other.Standard);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::DCL.ECSComponents.PBPlayerInputMovement.Types.StandardMovement subBuilder = new global::DCL.ECSComponents.PBPlayerInputMovement.Types.StandardMovement();
            if (modeCase_ == ModeOneofCase.Standard) {
              subBuilder.MergeFrom(Standard);
            }
            input.ReadMessage(subBuilder);
            Standard = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::DCL.ECSComponents.PBPlayerInputMovement.Types.StandardMovement subBuilder = new global::DCL.ECSComponents.PBPlayerInputMovement.Types.StandardMovement();
            if (modeCase_ == ModeOneofCase.Standard) {
              subBuilder.MergeFrom(Standard);
            }
            input.ReadMessage(subBuilder);
            Standard = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the PBPlayerInputMovement message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// when a boolean = false (default) the message is ignored and doesn't consume bandwidth
      /// </summary>
      public sealed partial class StandardMovement : pb::IMessage<StandardMovement>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<StandardMovement> _parser = new pb::MessageParser<StandardMovement>(() => new StandardMovement());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<StandardMovement> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::DCL.ECSComponents.PBPlayerInputMovement.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public StandardMovement() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public StandardMovement(StandardMovement other) : this() {
          disableAll_ = other.disableAll_;
          disableWalk_ = other.disableWalk_;
          disableRun_ = other.disableRun_;
          disableJump_ = other.disableJump_;
          disableEmote_ = other.disableEmote_;
          disableCamera_ = other.disableCamera_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public StandardMovement Clone() {
          return new StandardMovement(this);
        }

        /// <summary>Field number for the "disable_all" field.</summary>
        public const int DisableAllFieldNumber = 1;
        private bool disableAll_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool DisableAll {
          get { return disableAll_; }
          set {
            disableAll_ = value;
          }
        }

        /// <summary>Field number for the "disable_walk" field.</summary>
        public const int DisableWalkFieldNumber = 2;
        private bool disableWalk_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool DisableWalk {
          get { return disableWalk_; }
          set {
            disableWalk_ = value;
          }
        }

        /// <summary>Field number for the "disable_run" field.</summary>
        public const int DisableRunFieldNumber = 3;
        private bool disableRun_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool DisableRun {
          get { return disableRun_; }
          set {
            disableRun_ = value;
          }
        }

        /// <summary>Field number for the "disable_jump" field.</summary>
        public const int DisableJumpFieldNumber = 4;
        private bool disableJump_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool DisableJump {
          get { return disableJump_; }
          set {
            disableJump_ = value;
          }
        }

        /// <summary>Field number for the "disable_emote" field.</summary>
        public const int DisableEmoteFieldNumber = 5;
        private bool disableEmote_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool DisableEmote {
          get { return disableEmote_; }
          set {
            disableEmote_ = value;
          }
        }

        /// <summary>Field number for the "disable_camera" field.</summary>
        public const int DisableCameraFieldNumber = 6;
        private bool disableCamera_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool DisableCamera {
          get { return disableCamera_; }
          set {
            disableCamera_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as StandardMovement);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(StandardMovement other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (DisableAll != other.DisableAll) return false;
          if (DisableWalk != other.DisableWalk) return false;
          if (DisableRun != other.DisableRun) return false;
          if (DisableJump != other.DisableJump) return false;
          if (DisableEmote != other.DisableEmote) return false;
          if (DisableCamera != other.DisableCamera) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (DisableAll != false) hash ^= DisableAll.GetHashCode();
          if (DisableWalk != false) hash ^= DisableWalk.GetHashCode();
          if (DisableRun != false) hash ^= DisableRun.GetHashCode();
          if (DisableJump != false) hash ^= DisableJump.GetHashCode();
          if (DisableEmote != false) hash ^= DisableEmote.GetHashCode();
          if (DisableCamera != false) hash ^= DisableCamera.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (DisableAll != false) {
            output.WriteRawTag(8);
            output.WriteBool(DisableAll);
          }
          if (DisableWalk != false) {
            output.WriteRawTag(16);
            output.WriteBool(DisableWalk);
          }
          if (DisableRun != false) {
            output.WriteRawTag(24);
            output.WriteBool(DisableRun);
          }
          if (DisableJump != false) {
            output.WriteRawTag(32);
            output.WriteBool(DisableJump);
          }
          if (DisableEmote != false) {
            output.WriteRawTag(40);
            output.WriteBool(DisableEmote);
          }
          if (DisableCamera != false) {
            output.WriteRawTag(48);
            output.WriteBool(DisableCamera);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (DisableAll != false) {
            output.WriteRawTag(8);
            output.WriteBool(DisableAll);
          }
          if (DisableWalk != false) {
            output.WriteRawTag(16);
            output.WriteBool(DisableWalk);
          }
          if (DisableRun != false) {
            output.WriteRawTag(24);
            output.WriteBool(DisableRun);
          }
          if (DisableJump != false) {
            output.WriteRawTag(32);
            output.WriteBool(DisableJump);
          }
          if (DisableEmote != false) {
            output.WriteRawTag(40);
            output.WriteBool(DisableEmote);
          }
          if (DisableCamera != false) {
            output.WriteRawTag(48);
            output.WriteBool(DisableCamera);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (DisableAll != false) {
            size += 1 + 1;
          }
          if (DisableWalk != false) {
            size += 1 + 1;
          }
          if (DisableRun != false) {
            size += 1 + 1;
          }
          if (DisableJump != false) {
            size += 1 + 1;
          }
          if (DisableEmote != false) {
            size += 1 + 1;
          }
          if (DisableCamera != false) {
            size += 1 + 1;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(StandardMovement other) {
          if (other == null) {
            return;
          }
          if (other.DisableAll != false) {
            DisableAll = other.DisableAll;
          }
          if (other.DisableWalk != false) {
            DisableWalk = other.DisableWalk;
          }
          if (other.DisableRun != false) {
            DisableRun = other.DisableRun;
          }
          if (other.DisableJump != false) {
            DisableJump = other.DisableJump;
          }
          if (other.DisableEmote != false) {
            DisableEmote = other.DisableEmote;
          }
          if (other.DisableCamera != false) {
            DisableCamera = other.DisableCamera;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                DisableAll = input.ReadBool();
                break;
              }
              case 16: {
                DisableWalk = input.ReadBool();
                break;
              }
              case 24: {
                DisableRun = input.ReadBool();
                break;
              }
              case 32: {
                DisableJump = input.ReadBool();
                break;
              }
              case 40: {
                DisableEmote = input.ReadBool();
                break;
              }
              case 48: {
                DisableCamera = input.ReadBool();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                DisableAll = input.ReadBool();
                break;
              }
              case 16: {
                DisableWalk = input.ReadBool();
                break;
              }
              case 24: {
                DisableRun = input.ReadBool();
                break;
              }
              case 32: {
                DisableJump = input.ReadBool();
                break;
              }
              case 40: {
                DisableEmote = input.ReadBool();
                break;
              }
              case 48: {
                DisableCamera = input.ReadBool();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
