// <auto-generated>
//   Generated by protoc-gen-bitwise. DO NOT EDIT.
//   Source: decentraland/pulse/pulse_comms.proto
// </auto-generated>

using Decentraland.Networking.Bitwise;

namespace Decentraland.Pulse
{
    public partial class PlayerStateDeltaTier0
    {
        private float? _positionX;
        /// <summary>Float accessor for <see cref="PositionX"/>. Range [0.0f, 16.0f], 8 bits, step ≈ 0.0627451.</summary>
        public float PositionXQuantized
        {
            get => _positionX ??= Quantize.Decode(PositionX, 0.0f, 16.0f, 8);
            set { _positionX = value; PositionX = Quantize.Encode(value, 0.0f, 16.0f, 8); }
        }

        private float? _positionY;
        /// <summary>Float accessor for <see cref="PositionY"/>. Range [0.0f, 200.0f], 13 bits, step ≈ 0.024417.</summary>
        public float PositionYQuantized
        {
            get => _positionY ??= Quantize.Decode(PositionY, 0.0f, 200.0f, 13);
            set { _positionY = value; PositionY = Quantize.Encode(value, 0.0f, 200.0f, 13); }
        }

        private float? _positionZ;
        /// <summary>Float accessor for <see cref="PositionZ"/>. Range [0.0f, 16.0f], 8 bits, step ≈ 0.0627451.</summary>
        public float PositionZQuantized
        {
            get => _positionZ ??= Quantize.Decode(PositionZ, 0.0f, 16.0f, 8);
            set { _positionZ = value; PositionZ = Quantize.Encode(value, 0.0f, 16.0f, 8); }
        }

        private float? _velocityX;
        /// <summary>Float accessor for <see cref="VelocityX"/>. Range [-50.0f, 50.0f], 8 bits, step ≈ 0.392157.</summary>
        public float VelocityXQuantized
        {
            get => _velocityX ??= Quantize.Decode(VelocityX, -50.0f, 50.0f, 8);
            set { _velocityX = value; VelocityX = Quantize.Encode(value, -50.0f, 50.0f, 8); }
        }

        private float? _velocityY;
        /// <summary>Float accessor for <see cref="VelocityY"/>. Range [-50.0f, 50.0f], 8 bits, step ≈ 0.392157.</summary>
        public float VelocityYQuantized
        {
            get => _velocityY ??= Quantize.Decode(VelocityY, -50.0f, 50.0f, 8);
            set { _velocityY = value; VelocityY = Quantize.Encode(value, -50.0f, 50.0f, 8); }
        }

        private float? _velocityZ;
        /// <summary>Float accessor for <see cref="VelocityZ"/>. Range [-50.0f, 50.0f], 8 bits, step ≈ 0.392157.</summary>
        public float VelocityZQuantized
        {
            get => _velocityZ ??= Quantize.Decode(VelocityZ, -50.0f, 50.0f, 8);
            set { _velocityZ = value; VelocityZ = Quantize.Encode(value, -50.0f, 50.0f, 8); }
        }

        private float? _rotationY;
        /// <summary>Float accessor for <see cref="RotationY"/>. Range [0.0f, 360.0f], 7 bits, step ≈ 2.83465.</summary>
        public float RotationYQuantized
        {
            get => _rotationY ??= Quantize.Decode(RotationY, 0.0f, 360.0f, 7);
            set { _rotationY = value; RotationY = Quantize.Encode(value, 0.0f, 360.0f, 7); }
        }

        private float? _movementBlend;
        /// <summary>Float accessor for <see cref="MovementBlend"/>. Range [0.0f, 1.0f], 4 bits, step ≈ 0.0666667.</summary>
        public float MovementBlendQuantized
        {
            get => _movementBlend ??= Quantize.Decode(MovementBlend, 0.0f, 1.0f, 4);
            set { _movementBlend = value; MovementBlend = Quantize.Encode(value, 0.0f, 1.0f, 4); }
        }

        private float? _slideBlend;
        /// <summary>Float accessor for <see cref="SlideBlend"/>. Range [0.0f, 1.0f], 4 bits, step ≈ 0.0666667.</summary>
        public float SlideBlendQuantized
        {
            get => _slideBlend ??= Quantize.Decode(SlideBlend, 0.0f, 1.0f, 4);
            set { _slideBlend = value; SlideBlend = Quantize.Encode(value, 0.0f, 1.0f, 4); }
        }

        private float? _headYaw;
        /// <summary>Float accessor for <see cref="HeadYaw"/>. Range [0.0f, 360.0f], 7 bits, step ≈ 2.83465.</summary>
        public float HeadYawQuantized
        {
            get => _headYaw ??= Quantize.Decode(HeadYaw, 0.0f, 360.0f, 7);
            set { _headYaw = value; HeadYaw = Quantize.Encode(value, 0.0f, 360.0f, 7); }
        }

        private float? _headPitch;
        /// <summary>Float accessor for <see cref="HeadPitch"/>. Range [0.0f, 180.0f], 6 bits, step ≈ 2.85714.</summary>
        public float HeadPitchQuantized
        {
            get => _headPitch ??= Quantize.Decode(HeadPitch, 0.0f, 180.0f, 6);
            set { _headPitch = value; HeadPitch = Quantize.Encode(value, 0.0f, 180.0f, 6); }
        }

        /// <summary>Clears all cached decoded values. Call after mutating raw uint32 fields directly.</summary>
        public void ResetDecodedCache()
        {
            _positionX = null;
            _positionY = null;
            _positionZ = null;
            _velocityX = null;
            _velocityY = null;
            _velocityZ = null;
            _rotationY = null;
            _movementBlend = null;
            _slideBlend = null;
            _headYaw = null;
            _headPitch = null;
        }
    }


} // namespace Decentraland.Pulse
