// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: decentraland/common/quantization_example.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Decentraland.Common {

  /// <summary>Holder for reflection information generated from decentraland/common/quantization_example.proto</summary>
  public static partial class QuantizationExampleReflection {

    #region Descriptor
    /// <summary>File descriptor for decentraland/common/quantization_example.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QuantizationExampleReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci5kZWNlbnRyYWxhbmQvY29tbW9uL3F1YW50aXphdGlvbl9leGFtcGxlLnBy",
            "b3RvEhNkZWNlbnRyYWxhbmQuY29tbW9uGiFkZWNlbnRyYWxhbmQvY29tbW9u",
            "L29wdGlvbnMucHJvdG8ingEKDVBvc2l0aW9uRGVsdGESHAoCZHgYASABKA1C",
            "EIq1GAwNAADIwhUAAMhCGBASHAoCZHkYAiABKA1CEIq1GAwNAADIwhUAAMhC",
            "GBASHAoCZHoYAyABKA1CEIq1GAwNAADIwhUAAMhCGBASGQoJZW50aXR5X2lk",
            "GAQgASgNQgaStRgCCBQSGAoIc2VxdWVuY2UYBSABKA1CBpK1GAIIDCKjAQoL",
            "UGxheWVySW5wdXQSIAoGbW92ZV94GAEgASgNQhCKtRgMDQAAgL8VAACAPxgI",
            "EiAKBm1vdmVfehgCIAEoDUIQirUYDA0AAIC/FQAAgD8YCBIdCgN5YXcYAyAB",
            "KA1CEIq1GAwNAAA0wxUAADRDGAwSFwoHYnV0dG9ucxgEIAEoDUIGkrUYAggI",
            "EhgKCHNlcXVlbmNlGAUgASgNQgaStRgCCAwikAIKE0F2YXRhclN0YXRlU25h",
            "cHNob3QSGwoBeBgBIAEoDUIQirUYDA0AAIDFFQAAgEUYEBIbCgF5GAIgASgN",
            "QhCKtRgMDQAAgMMVAACAQxgOEhsKAXoYAyABKA1CEIq1GAwNAACAxRUAAIBF",
            "GBASHwoFcGl0Y2gYBCABKA1CEIq1GAwNAAC0whUAALRCGAoSHQoDeWF3GAUg",
            "ASgNQhCKtRgMDQAANMMVAAA0QxgMEhkKCWVudGl0eV9pZBgGIAEoDUIGkrUY",
            "AggUEh8KD2FuaW1hdGlvbl9zdGF0ZRgHIAEoDUIGkrUYAggGEhMKC2lzX2dy",
            "b3VuZGVkGAggASgIEhEKCXRpbWVzdGFtcBgJIAEoASpkCgtCdXR0b25GbGFn",
            "cxILCgdCRl9OT05FEAASCwoHQkZfSlVNUBABEg0KCUJGX1NQUklOVBACEg8K",
            "C0JGX0lOVEVSQUNUEAQSDAoIQkZfRU1PVEUQCBINCglCRl9DUk9VQ0gQEGIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Decentraland.Common.OptionsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Decentraland.Common.ButtonFlags), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Decentraland.Common.PositionDelta), global::Decentraland.Common.PositionDelta.Parser, new[]{ "Dx", "Dy", "Dz", "EntityId", "Sequence" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Decentraland.Common.PlayerInput), global::Decentraland.Common.PlayerInput.Parser, new[]{ "MoveX", "MoveZ", "Yaw", "Buttons", "Sequence" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Decentraland.Common.AvatarStateSnapshot), global::Decentraland.Common.AvatarStateSnapshot.Parser, new[]{ "X", "Y", "Z", "Pitch", "Yaw", "EntityId", "AnimationState", "IsGrounded", "Timestamp" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Bitmask values for PlayerInput.buttons.
  /// </summary>
  public enum ButtonFlags {
    [pbr::OriginalName("BF_NONE")] BfNone = 0,
    /// <summary>
    /// bit 0
    /// </summary>
    [pbr::OriginalName("BF_JUMP")] BfJump = 1,
    /// <summary>
    /// bit 1
    /// </summary>
    [pbr::OriginalName("BF_SPRINT")] BfSprint = 2,
    /// <summary>
    /// bit 2
    /// </summary>
    [pbr::OriginalName("BF_INTERACT")] BfInteract = 4,
    /// <summary>
    /// bit 3
    /// </summary>
    [pbr::OriginalName("BF_EMOTE")] BfEmote = 8,
    /// <summary>
    /// bit 4
    /// </summary>
    [pbr::OriginalName("BF_CROUCH")] BfCrouch = 16,
  }

  #endregion

  #region Messages
  /// <summary>
  /// ---------------------------------------------------------------------------
  /// PositionDelta — Δ position relative to last acknowledged full snapshot.
  ///
  /// Sent every client tick (~10 Hz) on Channel 1.
  ///
  ///  Field       | Type   | Range          | Q bits | Wire worst-case
  ///  ------------|--------|----------------|--------|-----------------------
  ///  dx          | uint32 | [-100, 100]    |   16   | tag 1B + varint 3B = 4B
  ///  dy          | uint32 | [-100, 100]    |   16   | tag 1B + varint 3B = 4B
  ///  dz          | uint32 | [-100, 100]    |   16   | tag 1B + varint 3B = 4B
  ///  entity_id   | uint32 | [0, 1 048 575] |   20   | tag 1B + varint 3B = 4B
  ///  sequence    | uint32 | [0,     4 095] |   12   | tag 1B + varint 2B = 3B
  ///  ---------------------------------------------------------------------------
  ///  Worst-case: 19 B  (vs. 20 B raw: 3×float + 2×uint32)
  ///  Step: dx/dy/dz ≈ 0.003 units
  /// ---------------------------------------------------------------------------
  /// </summary>
  public sealed partial class PositionDelta : pb::IMessage<PositionDelta>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PositionDelta> _parser = new pb::MessageParser<PositionDelta>(() => new PositionDelta());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PositionDelta> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Decentraland.Common.QuantizationExampleReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PositionDelta() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PositionDelta(PositionDelta other) : this() {
      dx_ = other.dx_;
      dy_ = other.dy_;
      dz_ = other.dz_;
      entityId_ = other.entityId_;
      sequence_ = other.sequence_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PositionDelta Clone() {
      return new PositionDelta(this);
    }

    /// <summary>Field number for the "dx" field.</summary>
    public const int DxFieldNumber = 1;
    private uint dx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Dx {
      get { return dx_; }
      set {
        dx_ = value;
      }
    }

    /// <summary>Field number for the "dy" field.</summary>
    public const int DyFieldNumber = 2;
    private uint dy_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Dy {
      get { return dy_; }
      set {
        dy_ = value;
      }
    }

    /// <summary>Field number for the "dz" field.</summary>
    public const int DzFieldNumber = 3;
    private uint dz_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Dz {
      get { return dz_; }
      set {
        dz_ = value;
      }
    }

    /// <summary>Field number for the "entity_id" field.</summary>
    public const int EntityIdFieldNumber = 4;
    private uint entityId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EntityId {
      get { return entityId_; }
      set {
        entityId_ = value;
      }
    }

    /// <summary>Field number for the "sequence" field.</summary>
    public const int SequenceFieldNumber = 5;
    private uint sequence_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Sequence {
      get { return sequence_; }
      set {
        sequence_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PositionDelta);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PositionDelta other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Dx != other.Dx) return false;
      if (Dy != other.Dy) return false;
      if (Dz != other.Dz) return false;
      if (EntityId != other.EntityId) return false;
      if (Sequence != other.Sequence) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Dx != 0) hash ^= Dx.GetHashCode();
      if (Dy != 0) hash ^= Dy.GetHashCode();
      if (Dz != 0) hash ^= Dz.GetHashCode();
      if (EntityId != 0) hash ^= EntityId.GetHashCode();
      if (Sequence != 0) hash ^= Sequence.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Dx != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Dx);
      }
      if (Dy != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Dy);
      }
      if (Dz != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Dz);
      }
      if (EntityId != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(EntityId);
      }
      if (Sequence != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Sequence);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Dx != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Dx);
      }
      if (Dy != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Dy);
      }
      if (Dz != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Dz);
      }
      if (EntityId != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(EntityId);
      }
      if (Sequence != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Sequence);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Dx != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Dx);
      }
      if (Dy != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Dy);
      }
      if (Dz != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Dz);
      }
      if (EntityId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EntityId);
      }
      if (Sequence != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Sequence);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PositionDelta other) {
      if (other == null) {
        return;
      }
      if (other.Dx != 0) {
        Dx = other.Dx;
      }
      if (other.Dy != 0) {
        Dy = other.Dy;
      }
      if (other.Dz != 0) {
        Dz = other.Dz;
      }
      if (other.EntityId != 0) {
        EntityId = other.EntityId;
      }
      if (other.Sequence != 0) {
        Sequence = other.Sequence;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Dx = input.ReadUInt32();
            break;
          }
          case 16: {
            Dy = input.ReadUInt32();
            break;
          }
          case 24: {
            Dz = input.ReadUInt32();
            break;
          }
          case 32: {
            EntityId = input.ReadUInt32();
            break;
          }
          case 40: {
            Sequence = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Dx = input.ReadUInt32();
            break;
          }
          case 16: {
            Dy = input.ReadUInt32();
            break;
          }
          case 24: {
            Dz = input.ReadUInt32();
            break;
          }
          case 32: {
            EntityId = input.ReadUInt32();
            break;
          }
          case 40: {
            Sequence = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// ---------------------------------------------------------------------------
  /// PlayerInput — client input snapshot for server-side reconciliation.
  ///
  /// Sent every client frame (~30 Hz) on Channel 1.
  ///
  ///  Field       | Type   | Range          | Q bits | Wire worst-case
  ///  ------------|--------|----------------|--------|-----------------------
  ///  move_x      | uint32 | [-1, 1]        |    8   | tag 1B + varint 2B = 3B
  ///  move_z      | uint32 | [-1, 1]        |    8   | tag 1B + varint 2B = 3B
  ///  yaw         | uint32 | [-180, 180]    |   12   | tag 1B + varint 2B = 3B
  ///  buttons     | uint32 | bitmask        |    8   | tag 1B + varint 2B = 3B
  ///  sequence    | uint32 | [0, 4 095]     |   12   | tag 1B + varint 2B = 3B
  ///  ---------------------------------------------------------------------------
  ///  Worst-case: 15 B  (vs. 20 B raw: 3×float + 2×uint32)
  ///  Step: move_x/move_z ≈ 0.008; yaw ≈ 0.088°
  /// ---------------------------------------------------------------------------
  /// </summary>
  public sealed partial class PlayerInput : pb::IMessage<PlayerInput>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerInput> _parser = new pb::MessageParser<PlayerInput>(() => new PlayerInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Decentraland.Common.QuantizationExampleReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerInput(PlayerInput other) : this() {
      moveX_ = other.moveX_;
      moveZ_ = other.moveZ_;
      yaw_ = other.yaw_;
      buttons_ = other.buttons_;
      sequence_ = other.sequence_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerInput Clone() {
      return new PlayerInput(this);
    }

    /// <summary>Field number for the "move_x" field.</summary>
    public const int MoveXFieldNumber = 1;
    private uint moveX_;
    /// <summary>
    /// Normalised joystick axes in [-1, 1].
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MoveX {
      get { return moveX_; }
      set {
        moveX_ = value;
      }
    }

    /// <summary>Field number for the "move_z" field.</summary>
    public const int MoveZFieldNumber = 2;
    private uint moveZ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MoveZ {
      get { return moveZ_; }
      set {
        moveZ_ = value;
      }
    }

    /// <summary>Field number for the "yaw" field.</summary>
    public const int YawFieldNumber = 3;
    private uint yaw_;
    /// <summary>
    /// Horizontal look direction in degrees.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Yaw {
      get { return yaw_; }
      set {
        yaw_ = value;
      }
    }

    /// <summary>Field number for the "buttons" field.</summary>
    public const int ButtonsFieldNumber = 4;
    private uint buttons_;
    /// <summary>
    /// Bitmask of active buttons (see ButtonFlags below).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Buttons {
      get { return buttons_; }
      set {
        buttons_ = value;
      }
    }

    /// <summary>Field number for the "sequence" field.</summary>
    public const int SequenceFieldNumber = 5;
    private uint sequence_;
    /// <summary>
    /// Rolling input sequence number used by the server for reconciliation.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Sequence {
      get { return sequence_; }
      set {
        sequence_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MoveX != other.MoveX) return false;
      if (MoveZ != other.MoveZ) return false;
      if (Yaw != other.Yaw) return false;
      if (Buttons != other.Buttons) return false;
      if (Sequence != other.Sequence) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MoveX != 0) hash ^= MoveX.GetHashCode();
      if (MoveZ != 0) hash ^= MoveZ.GetHashCode();
      if (Yaw != 0) hash ^= Yaw.GetHashCode();
      if (Buttons != 0) hash ^= Buttons.GetHashCode();
      if (Sequence != 0) hash ^= Sequence.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MoveX != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MoveX);
      }
      if (MoveZ != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(MoveZ);
      }
      if (Yaw != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Yaw);
      }
      if (Buttons != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Buttons);
      }
      if (Sequence != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Sequence);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MoveX != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MoveX);
      }
      if (MoveZ != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(MoveZ);
      }
      if (Yaw != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Yaw);
      }
      if (Buttons != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Buttons);
      }
      if (Sequence != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Sequence);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MoveX != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MoveX);
      }
      if (MoveZ != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MoveZ);
      }
      if (Yaw != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Yaw);
      }
      if (Buttons != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Buttons);
      }
      if (Sequence != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Sequence);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerInput other) {
      if (other == null) {
        return;
      }
      if (other.MoveX != 0) {
        MoveX = other.MoveX;
      }
      if (other.MoveZ != 0) {
        MoveZ = other.MoveZ;
      }
      if (other.Yaw != 0) {
        Yaw = other.Yaw;
      }
      if (other.Buttons != 0) {
        Buttons = other.Buttons;
      }
      if (other.Sequence != 0) {
        Sequence = other.Sequence;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MoveX = input.ReadUInt32();
            break;
          }
          case 16: {
            MoveZ = input.ReadUInt32();
            break;
          }
          case 24: {
            Yaw = input.ReadUInt32();
            break;
          }
          case 32: {
            Buttons = input.ReadUInt32();
            break;
          }
          case 40: {
            Sequence = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MoveX = input.ReadUInt32();
            break;
          }
          case 16: {
            MoveZ = input.ReadUInt32();
            break;
          }
          case 24: {
            Yaw = input.ReadUInt32();
            break;
          }
          case 32: {
            Buttons = input.ReadUInt32();
            break;
          }
          case 40: {
            Sequence = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// ---------------------------------------------------------------------------
  /// AvatarStateSnapshot — full authoritative state, sent on Channel 0 (reliable)
  /// or on resync requests.  Demonstrates wider ranges and mixed encodings.
  ///
  ///  Field            | Type   | Range            | Q bits | Wire worst-case
  ///  -----------------|--------|------------------|--------|-----------------------
  ///  x                | uint32 | [-4096, 4096]    |   16   | tag 1B + varint 3B = 4B
  ///  y                | uint32 | [-256,   256]    |   14   | tag 1B + varint 2B = 3B
  ///  z                | uint32 | [-4096, 4096]    |   16   | tag 1B + varint 3B = 4B
  ///  pitch            | uint32 | [-90,    90]     |   10   | tag 1B + varint 2B = 3B
  ///  yaw              | uint32 | [-180,  180]     |   12   | tag 1B + varint 2B = 3B
  ///  entity_id        | uint32 | [0, 1 048 575]   |   20   | tag 1B + varint 3B = 4B
  ///  animation_state  | uint32 | [0,       63]    |    6   | tag 1B + varint 1B = 2B
  ///  is_grounded      | bool   | —                |   —    | tag 1B + varint 1B = 2B
  ///  timestamp        | double | —                |   —    | tag 1B + fixed64  8B = 9B
  ///  ---------------------------------------------------------------------------
  ///  Worst-case: 34 B  (vs. 45 B raw: 5×float + 2×uint32 + bool + double)
  ///  Step: x/z ≈ 0.125 units; y ≈ 0.031 units; pitch ≈ 0.176°; yaw ≈ 0.088°
  /// ---------------------------------------------------------------------------
  /// </summary>
  public sealed partial class AvatarStateSnapshot : pb::IMessage<AvatarStateSnapshot>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AvatarStateSnapshot> _parser = new pb::MessageParser<AvatarStateSnapshot>(() => new AvatarStateSnapshot());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AvatarStateSnapshot> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Decentraland.Common.QuantizationExampleReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AvatarStateSnapshot() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AvatarStateSnapshot(AvatarStateSnapshot other) : this() {
      x_ = other.x_;
      y_ = other.y_;
      z_ = other.z_;
      pitch_ = other.pitch_;
      yaw_ = other.yaw_;
      entityId_ = other.entityId_;
      animationState_ = other.animationState_;
      isGrounded_ = other.isGrounded_;
      timestamp_ = other.timestamp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AvatarStateSnapshot Clone() {
      return new AvatarStateSnapshot(this);
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 1;
    private uint x_;
    /// <summary>
    /// World-space position.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 2;
    private uint y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    /// <summary>Field number for the "z" field.</summary>
    public const int ZFieldNumber = 3;
    private uint z_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Z {
      get { return z_; }
      set {
        z_ = value;
      }
    }

    /// <summary>Field number for the "pitch" field.</summary>
    public const int PitchFieldNumber = 4;
    private uint pitch_;
    /// <summary>
    /// View angles.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Pitch {
      get { return pitch_; }
      set {
        pitch_ = value;
      }
    }

    /// <summary>Field number for the "yaw" field.</summary>
    public const int YawFieldNumber = 5;
    private uint yaw_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Yaw {
      get { return yaw_; }
      set {
        yaw_ = value;
      }
    }

    /// <summary>Field number for the "entity_id" field.</summary>
    public const int EntityIdFieldNumber = 6;
    private uint entityId_;
    /// <summary>
    /// Identity and animation state.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EntityId {
      get { return entityId_; }
      set {
        entityId_ = value;
      }
    }

    /// <summary>Field number for the "animation_state" field.</summary>
    public const int AnimationStateFieldNumber = 7;
    private uint animationState_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint AnimationState {
      get { return animationState_; }
      set {
        animationState_ = value;
      }
    }

    /// <summary>Field number for the "is_grounded" field.</summary>
    public const int IsGroundedFieldNumber = 8;
    private bool isGrounded_;
    /// <summary>
    /// Un-annotated fields — encoded at their natural width.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsGrounded {
      get { return isGrounded_; }
      set {
        isGrounded_ = value;
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 9;
    private double timestamp_;
    /// <summary>
    /// server epoch milliseconds
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AvatarStateSnapshot);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AvatarStateSnapshot other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (X != other.X) return false;
      if (Y != other.Y) return false;
      if (Z != other.Z) return false;
      if (Pitch != other.Pitch) return false;
      if (Yaw != other.Yaw) return false;
      if (EntityId != other.EntityId) return false;
      if (AnimationState != other.AnimationState) return false;
      if (IsGrounded != other.IsGrounded) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Timestamp, other.Timestamp)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (X != 0) hash ^= X.GetHashCode();
      if (Y != 0) hash ^= Y.GetHashCode();
      if (Z != 0) hash ^= Z.GetHashCode();
      if (Pitch != 0) hash ^= Pitch.GetHashCode();
      if (Yaw != 0) hash ^= Yaw.GetHashCode();
      if (EntityId != 0) hash ^= EntityId.GetHashCode();
      if (AnimationState != 0) hash ^= AnimationState.GetHashCode();
      if (IsGrounded != false) hash ^= IsGrounded.GetHashCode();
      if (Timestamp != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Timestamp);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (X != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(X);
      }
      if (Y != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Y);
      }
      if (Z != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Z);
      }
      if (Pitch != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Pitch);
      }
      if (Yaw != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Yaw);
      }
      if (EntityId != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(EntityId);
      }
      if (AnimationState != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(AnimationState);
      }
      if (IsGrounded != false) {
        output.WriteRawTag(64);
        output.WriteBool(IsGrounded);
      }
      if (Timestamp != 0D) {
        output.WriteRawTag(73);
        output.WriteDouble(Timestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (X != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(X);
      }
      if (Y != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Y);
      }
      if (Z != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Z);
      }
      if (Pitch != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Pitch);
      }
      if (Yaw != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Yaw);
      }
      if (EntityId != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(EntityId);
      }
      if (AnimationState != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(AnimationState);
      }
      if (IsGrounded != false) {
        output.WriteRawTag(64);
        output.WriteBool(IsGrounded);
      }
      if (Timestamp != 0D) {
        output.WriteRawTag(73);
        output.WriteDouble(Timestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (X != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(X);
      }
      if (Y != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Y);
      }
      if (Z != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Z);
      }
      if (Pitch != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Pitch);
      }
      if (Yaw != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Yaw);
      }
      if (EntityId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EntityId);
      }
      if (AnimationState != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AnimationState);
      }
      if (IsGrounded != false) {
        size += 1 + 1;
      }
      if (Timestamp != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AvatarStateSnapshot other) {
      if (other == null) {
        return;
      }
      if (other.X != 0) {
        X = other.X;
      }
      if (other.Y != 0) {
        Y = other.Y;
      }
      if (other.Z != 0) {
        Z = other.Z;
      }
      if (other.Pitch != 0) {
        Pitch = other.Pitch;
      }
      if (other.Yaw != 0) {
        Yaw = other.Yaw;
      }
      if (other.EntityId != 0) {
        EntityId = other.EntityId;
      }
      if (other.AnimationState != 0) {
        AnimationState = other.AnimationState;
      }
      if (other.IsGrounded != false) {
        IsGrounded = other.IsGrounded;
      }
      if (other.Timestamp != 0D) {
        Timestamp = other.Timestamp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            X = input.ReadUInt32();
            break;
          }
          case 16: {
            Y = input.ReadUInt32();
            break;
          }
          case 24: {
            Z = input.ReadUInt32();
            break;
          }
          case 32: {
            Pitch = input.ReadUInt32();
            break;
          }
          case 40: {
            Yaw = input.ReadUInt32();
            break;
          }
          case 48: {
            EntityId = input.ReadUInt32();
            break;
          }
          case 56: {
            AnimationState = input.ReadUInt32();
            break;
          }
          case 64: {
            IsGrounded = input.ReadBool();
            break;
          }
          case 73: {
            Timestamp = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            X = input.ReadUInt32();
            break;
          }
          case 16: {
            Y = input.ReadUInt32();
            break;
          }
          case 24: {
            Z = input.ReadUInt32();
            break;
          }
          case 32: {
            Pitch = input.ReadUInt32();
            break;
          }
          case 40: {
            Yaw = input.ReadUInt32();
            break;
          }
          case 48: {
            EntityId = input.ReadUInt32();
            break;
          }
          case 56: {
            AnimationState = input.ReadUInt32();
            break;
          }
          case 64: {
            IsGrounded = input.ReadBool();
            break;
          }
          case 73: {
            Timestamp = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
