name: 'Auto Assign Reviewers'

on:
  workflow_dispatch:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  detect-pr-type:
    runs-on: ubuntu-latest
    outputs:
      is-feature: ${{ steps.check.outputs.is-feature }}
    steps:
      - name: Check PR type
        id: check
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const title = context.payload.pull_request.title || '';
            const isAutoReview = /^(fix|chore)(\(.*?\))?!?:/i.test(title);
            core.setOutput('is-feature', (!isAutoReview).toString());

  assign-devs:
    needs: detect-pr-type
    if: needs.detect-pr-type.outputs.is-feature == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@0a2c53d3721e4c5cfcce6afd4014aecc337979f6 # v2.0.2
        with:
          configuration-path: '.github/auto_assign_config_dev.yml'

  assign-qa:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@0a2c53d3721e4c5cfcce6afd4014aecc337979f6 # v2.0.2
        with:
          configuration-path: '.github/auto_assign_config_qa.yml'
