name: Unity Cloud Build Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
  # schedule:
  #  - cron: '10 0 * * 3'

jobs:
  get-info:
    name: Get Info
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      version: ${{ steps.get_version.outputs.next_short_version }}
      tag_version: ${{ steps.get_version.outputs.next_tag_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        uses: ./.github/actions/version

  # Run a clean build (no cache)
  build:
    name: Build Unity Cloud
    needs: get-info
    uses: ./.github/workflows/build-unitycloud.yml
    with:
      profile: none
      clean_build: true
      cache_strategy: none
      version: ${{ needs.get-info.outputs.next_short_version }}
      sentry_enabled: true
      is_release_build: true
      tag_version: ${{ needs.get-info.outputs.tag_version }}
    secrets: inherit
