name: Unity Mac Build IL2CPP

on:
  workflow_dispatch: {}
  
env:
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        include:
          - targetPlatform: StandaloneOSX
            dockerImage: macos-latest-xl


    name: Build
    runs-on: ${{ matrix.dockerImage }}
    steps:
      - name: Install PowerShell
        run: brew install powershell
      # This step is required if PowerShell is not pre-installed on the runner.

      - name: Set SHA env variable
        shell: pwsh
        run: |
            $eventName = "${{ github.event_name }}"

            if ($eventName -eq "push") {
                $LONG_SHA = "${{ github.sha }}"
                $SHORT_SHA = ($LONG_SHA).Substring(0, 7)
                Add-Content -Value "CUSTOM_SHA=$SHORT_SHA" -Path $env:GITHUB_ENV
                Write-Output $SHORT_SHA
            }
            elseif ($eventName -eq "pull_request") {
                $LONG_SHA = "${{ github.event.pull_request.head.sha }}"
                $SHORT_SHA = ($LONG_SHA).Substring(0, 7)
                Add-Content -Value "CUSTOM_SHA=$SHORT_SHA" -Path $env:GITHUB_ENV
                Write-Output $SHORT_SHA
            }
          
      - name: Set sentry env var
        shell: pwsh
        run: |
          $branchName = "${{ github.ref }}"
          $SENTRY_ENVIRONMENT = "branch"
          
          if ($branchName -eq 'refs/heads/main') {
            $SENTRY_ENVIRONMENT = "production"
          } elseif ($branchName -eq 'refs/heads/dev') {
            $SENTRY_ENVIRONMENT = "development"
          }
          
          Add-Content -Value "SENTRY_ENVIRONMENT=$SENTRY_ENVIRONMENT" -Path $env:GITHUB_ENV
          Write-Output $SENTRY_ENVIRONMENT
          
      - name: Enable or disable the upload of sentry debug symbols
        shell: pwsh
        run: |
          $branchName = "${{ github.ref }}"
          $uploadSymbols = "false"
          if ($branchName -eq 'refs/heads/main') {
            $uploadSymbols = "true"
          }
          Add-Content -Value "SENTRY_UPLOAD_DEBUG_SYMBOLS=$uploadSymbols" -Path $env:GITHUB_ENV
          Write-Output $uploadSymbols
            
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v3
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      - name: Restore Library cache
        uses: actions/cache@v3
        with:
          path: | 
            Explorer/Library
            !Explorer/Library/Bee/**
            !Explorer/Library/BuildPlayerData/**
          key: Library-Explorer-IL2CPP-${{ matrix.targetPlatform }}
          
      - uses: decentraland/unity-builder@0.9
        id: build
        timeout-minutes: 120
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: Explorer
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic
          customParameters: -sentryDsn ${{ secrets.SENTRY_DSN }} -sentryEnvironment ${{ env.SENTRY_ENVIRONMENT }} -sentryCliAuthToken ${{ secrets.SENTRY_CLI_AUTH_TOKEN }} -sentryUploadDebugSymbols ${{ env.SENTRY_UPLOAD_DEBUG_SYMBOLS }}
          
      # Tar build files to maintain file permissions
      - name: Tar MacOSX/Linux build files
        run: |
          echo 1. go into build dir
          cd build
          echo 2. delete unnecessary folder
          rm -r  ${{ matrix.targetPlatform }}/StandaloneOSX_BackUpThisFolder_ButDontShipItWithYourGame
          rm -r  ${{ matrix.targetPlatform }}/StandaloneOSX_BurstDebugInformation_DoNotShip
          echo 4. tar mac build folder + remove og files
          sudo tar -cvf "${{ matrix.targetPlatform }}.tar" "${{ matrix.targetPlatform }}"
          rm -r  ${{ matrix.targetPlatform }}
          echo 5. go back to src dir
          cd ..
          
      # Upload artifact
      - name: Upload mac artifact
        uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}.tar
          if-no-files-found: error