name: Unity Build

on:
  pull_request: {}
  push: { branches: [main] }

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        include:
          - targetPlatform: StandaloneWindows64
            dockerImage: windows-2019
          - targetPlatform: StandaloneOSX
            dockerImage: macos-latest


    name: Build
    runs-on: ${{ matrix.dockerImage }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v3
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      - name: Restore Library cache
        uses: actions/cache@v3
        with:
          path: Explorer/Library
          key: Library-Explorer-${{ matrix.targetPlatform }}

      # Configure test runner
      - uses: game-ci/unity-builder@v2
        id: build
        timeout-minutes: 120
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: Explorer
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Unity - Return License
        uses: game-ci/unity-return-license@v2.0.0
        if: always()


      # Upload artifact
      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build
          if-no-files-found: error