name: Unity Build

on:
  pull_request: {}
  push: { branches: [main] }

jobs:
  build:
    name: Build
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v3
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      # - name: Restore Library cache
      #   uses: actions/cache@v2
      #   with:
      #     path: Explorer/Library
      #     key: Library-Explorer-Windows

      # Configure test runner
      - uses: game-ci/unity-builder@v2
        id: build
        timeout-minutes: 45
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: Explorer
          targetPlatform: StandaloneWindows64

      - name: Print
        run: |
          dir
          cd build/StandaloneWindows64
          dir
          echo 'Output Name: ${{ steps.build.outputs.outputName }}'
          echo 'Project Version: ${{ steps.build.outputs.buildVersion }}'

      # Upload artifact
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build/StandaloneWindows64