name: Handle PR Closure

on:
  pull_request:
    types:
      - closed

jobs:
  handle-pr-closure:
    name: Handle PR Closure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if PR is merged
        id: check_if_merged
        run: echo "PR_MERGED=${{ github.event.pull_request.merged }}" >> $GITHUB_ENV

      - name: Delete Unity Cloud target if merged
        if: env.PR_MERGED == 'true'
        env:
          API_KEY: ${{ secrets.UNITY_CLOUD_API_KEY }}
          ORG_ID: ${{ secrets.UNITY_CLOUD_ORG_ID }}
          PROJECT_ID: ${{ secrets.UNITY_CLOUD_PROJECT_ID }}
        run: python -u scripts/cloudbuild/build.py --delete

      - name: Delete Unity Cloud target if closed without merging
        if: env.PR_MERGED != 'true'
        env:
          API_KEY: ${{ secrets.UNITY_CLOUD_API_KEY }}
          ORG_ID: ${{ secrets.UNITY_CLOUD_ORG_ID }}
          PROJECT_ID: ${{ secrets.UNITY_CLOUD_PROJECT_ID }}
        run: python -u scripts/cloudbuild/build.py --delete