name: Weekly Release

on:
  schedule:
    - cron: '10 0 * * 1'
  # For testing only!
  push:
    branches:
      - feat/unity-cloud-build

jobs:
  get-info:
    name: Get Info
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      full_version: ${{ steps.get_version.outputs.next_full_version }}
      tag_version: ${{ steps.get_version.outputs.next_tag_version }}
    steps:
      - name: Get latest version tag
        id: get_latest_version_tag
        run: echo "tag=$(git describe --tags --match='v[0-9]*'))" >> $GITHUB_OUTPUT

      - name: Get version
        id: get_version
        uses: ./.github/actions/version@feat/unity-cloud-build
        with:
          tag: ${{ steps.get_latest_version_tag.outputs.tag }}

  # Run a clean build (no cache)
  build:
    name: Build Unity Cloud
    needs: get-info
    #uses: decentraland/unity-explorer/.github/workflows/build-unitycloud.yml@main
    uses: decentraland/unity-explorer/.github/workflows/build-unitycloud.yml@feat/unity-cloud-build
    with:
      profile: none
      cache: false
      version: ${{ needs.get-info.outputs.full_version }}
    secrets: inherit

  generate-release-info:
    name: Generate release info
    runs-on: ubuntu-latest
    needs: [build, get-info]
    timeout-minutes: 5
    steps:
      - name: Apply tag to branch
        run: echo ${{ needs.get-info.outputs.tag_version }}
#        run: |
#          TAG=${{ needs.get-info.outputs.tag_version }}
#          git tag $TAG
#          git push origin $TAG

      - name: Create release notes
        run: echo "TODO - Generate release notes automatically from previous week"

      - name: Create release
        run: echo "TODO - Generate a new release with the new tag"